-- RPH Hub: Pendidikan Jasmani Tahun 3 source-first Activity + Induction Library.
-- Idempotent: existing keys are updated, not duplicated.
-- These rows are delivery wrappers. They never create Lesson Maps and never
-- replace the actual RPT / DSKP / textbook task selected for a lesson.

with patterns(
  pattern_key, pattern_name, source_words, technique_focus,
  game_name, game_rule, evidence, bbm
) as (
  values
    ('balance','Imbangan','imbangan,tapak sokongan,dirian tangan,kereta sorong',
      'membentuk tapak sokongan yang stabil, mengawal pusat graviti dan mengekalkan posisi akhir',
      'Patung Imbangan',
      'Murid bergerak ke penanda, membentuk imbangan yang ditetapkan pada kad dan membekukan posisi selama kiraan yang sesuai; mata diberi apabila posisi stabil serta ruang rakan tidak diganggu.',
      'posisi badan stabil, tapak sokongan dan kawalan semasa mula serta tamat',
      'Buku Teks, tilam gimnastik, kon, kad posisi, kad semak teknik'),
    ('spring_landing','Hambur dan Pendaratan','hambur,melonjak,mendarat,kanggaru,kaki ke tangan,tangan ke kaki',
      'menggunakan ayunan, tolakan dan pendaratan dengan lutut difleksi mengikut urutan kemahiran dalam sumber',
      'Jejak Pendaratan Senyap',
      'Murid melaksanakan kemahiran pada stesen bertanda dan memperoleh kad stesen apabila mendarat terkawal di zon sendiri; ketinggian atau alatan tidak ditambah.',
      'urutan tolakan, bentuk badan dan pendaratan terkawal',
      'Buku Teks, tilam gimnastik, gelung, kon, kad urutan'),
    ('rotation','Putaran dan Guling','guling,putaran badan,tenggiling',
      'mengikut fasa mula, pemindahan berat, putaran dan posisi akhir yang ditunjukkan dalam sumber',
      'Puzzle Fasa Guling',
      'Selepas percubaan, pasangan menyusun kad fasa mengikut gerakan yang baru dilakukan dan menunjukkan satu pembetulan sebelum percubaan berikutnya.',
      'urutan fasa, kawalan badan dan posisi akhir',
      'Buku Teks, tilam gimnastik, kad fasa, penanda ruang'),
    ('rhythmic_movement','Pergerakan Berirama','pergerakan berirama,ikut langkah,ikut gerak,rangkaian pergerakan,muzik',
      'menggabungkan langkah dan pergerakan badan mengikut kiraan, arah serta tempo yang ditetapkan dalam sumber',
      'Cermin Irama',
      'Seorang murid menjadi pemimpin dan seorang lagi menjadi cermin bagi rangkaian gerak Buku Teks; pasangan bertukar peranan selepas satu rangkaian lengkap dan menyemak ketepatan kiraan.',
      'ketepatan kiraan, urutan gerak, arah dan keselarasan pergerakan',
      'Buku Teks, audio atau alat perkusi, kad kiraan, penanda ruang'),
    ('invasion_game','Permainan Serangan','menghantar bola,menerima bola,mengadang,mengelecek,menjaring,permainan kategori serangan',
      'menghantar, menerima, mengelecek atau menjaring mengikut kemahiran serta situasi permainan kecil dalam sumber',
      'Bola ke Zon',
      'Kumpulan menggerakkan bola ke zon sasaran menggunakan kemahiran yang sedang dipelajari; mata hanya dikira selepas hantaran atau kawalan yang tepat dan semua murid mematuhi sempadan permainan.',
      'ketepatan kemahiran, pilihan ruang, kawalan bola dan kerjasama',
      'Buku Teks, bola lembut, kon, bib, gelung sasaran, kad peraturan'),
    ('net_game','Permainan Jaring','permainan kategori jaring,voli,menyangga,servis bawah,servis atas,pukulan pepat,pukulan kilas',
      'melaksanakan kemahiran menghantar, menerima, servis atau pukulan mengikut teknik pada halaman sumber',
      'Rali Sasaran',
      'Pasangan cuba mengekalkan rali atau menghantar objek ke zon sasaran dengan kemahiran Buku Teks; kiraan bermula semula jika teknik atau sempadan keselamatan tidak dipatuhi.',
      'posisi sedia, sentuhan atau pukulan terkawal, arah dan ketepatan sasaran',
      'Buku Teks, raket atau pemukul ringan, bola atau bulu tangkis, jaring rendah, kon sasaran'),
    ('striking_fielding','Pukul dan Memadang','memukul bola,menahan bola,balingan atas kepala,balingan bawah tangan,permainan kategori pukul',
      'memukul, membaling, menangkap atau menahan bola mengikut urutan dan situasi permainan dalam sumber',
      'Pukul–Kutip–Hantar',
      'Murid bergilir sebagai pemukul, pemadang dan penghantar; satu mata diberi apabila bola dikawal dan dihantar ke sasaran menggunakan kemahiran yang betul sebelum peranan bertukar.',
      'kontak atau tangkapan terkawal, arah, ketepatan dan pertukaran peranan',
      'Buku Teks, bola lembut, bet ringan, kon, gelung sasaran, bib'),
    ('running','Larian','berlari,lari pecut,kelajuan larian,jarak larian',
      'berlari pada jarak atau kelajuan yang ditetapkan sambil mengawal postur, ayunan tangan dan garisan penamat',
      'Lampu Isyarat Larian',
      'Murid bergerak pada kelajuan yang sepadan dengan kad warna dan menamatkan larian di zon sendiri; fokus diberi pada kawalan tempo dan teknik, bukan menyingkirkan peserta.',
      'postur, ayunan tangan, perubahan kelajuan dan kawalan di garisan akhir',
      'Buku Teks, kon, kad warna, penanda lorong, wisel'),
    ('jumping','Lompatan','melompat,lompatan,melepasi halangan,lonjak',
      'menggunakan lonjakan dan pendaratan yang sesuai untuk melepasi halangan atau mencapai zon yang ditetapkan dalam sumber',
      'Pulau Pendaratan',
      'Murid mengikut laluan lompatan Buku Teks dan mendarat dalam pulau bertanda; pasangan memeriksa posisi mendarat sebelum murid bergerak ke stesen seterusnya.',
      'lonjakan, koordinasi tangan dan kaki serta pendaratan seimbang',
      'Buku Teks, gelung, kon, halangan rendah, kad laluan'),
    ('throwing','Balingan dan Lontaran','membaling,melontar,melempar,baling objek,lempar objek',
      'membaling atau melontar objek yang ditetapkan ke arah sasaran dengan posisi badan dan pelepasan yang betul',
      'Sasaran Berlapis',
      'Murid membuat bilangan percubaan yang sama dari garisan Buku Teks dan merekod zon sasaran yang dicapai; objek hanya dikutip selepas isyarat guru.',
      'posisi badan, arah pelepasan, ketepatan dan pematuhan giliran',
      'Buku Teks, objek balingan yang sesuai, gelung sasaran, kon, kad rekod'),
    ('traditional_game','Permainan Tradisional','tarik upih,batak lampung,batu seremban,karom,permainan tradisional',
      'melaksanakan kemahiran serta peranan permainan tradisional mengikut peraturan dan alatan pada sumber',
      'Pusingan Warisan',
      'Kumpulan bermain satu pusingan pendek menggunakan peraturan Buku Teks, kemudian bertukar peranan sebagai pemain, pengadil kecil dan pencatat sebelum pusingan seterusnya.',
      'pelaksanaan kemahiran, kefahaman peraturan, kerjasama dan permainan adil',
      'Buku Teks, set permainan tradisional yang dinyatakan, kad peranan, papan skor'),
    ('strategy_game','Permainan Strategi','catur,dam,strategi permainan,buah catur,papan dam',
      'memilih gerakan yang sah, merancang tindakan seterusnya dan menerangkan sebab berdasarkan keadaan papan',
      'Cabaran Gerakan Terbaik',
      'Pasangan menerima satu kedudukan papan, memilih satu gerakan yang sah dan menerangkan sebab sebelum menyemak dengan kad jawapan atau guru.',
      'gerakan sah, sebab pemilihan dan tindak balas terhadap gerakan lawan',
      'Buku Teks, papan dan buah permainan, kad situasi, jam pasir'),
    ('warmup_pulse','Pemanasan Badan dan Nadi','memanaskan badan,pemanasan badan,kadar nadi,denyutan nadi',
      'melaksanakan urutan pemanasan badan dan membandingkan perubahan kadar nadi sebelum serta selepas aktiviti',
      'Detektif Nadi',
      'Murid melakukan urutan pemanasan daripada sumber, mengukur nadi pada masa yang ditetapkan dan memadankan rekod dengan keadaan sebelum atau selepas aktiviti tanpa membandingkan tubuh antara murid.',
      'urutan pemanasan, rekod nadi sendiri dan penerangan perubahan',
      'Buku Teks, jam randik, kad urutan, lembaran rekod kendiri'),
    ('cooldown_hydration','Penyejukan Badan dan Hidrasi','menyejukkan badan,penyejukan badan,hidrasi,pengambilan air',
      'melaksanakan urutan penyejukan badan serta memilih amalan pengambilan air yang sesuai selepas aktiviti',
      'Susun Rutin Pulih',
      'Kumpulan menyusun kad tindakan kepada urutan penyejukan dan hidrasi yang betul, kemudian melaksanakan urutan yang disahkan guru pada kadar terkawal.',
      'urutan tindakan, pernafasan terkawal dan sebab memilih amalan hidrasi',
      'Buku Teks, kad urutan, jam randik, bekas air murid'),
    ('aerobic','Kapasiti Aerobik','aerobik,daya tahan kardiovaskular,jantung dan paru,talk test',
      'melaksanakan rangkaian aerobik pada intensiti sederhana dan mengenal pasti respons badan yang selamat',
      'Litar Kiraan Aerobik',
      'Kumpulan bergerak melalui stesen gerak aerobik pada kiraan yang sama, menggunakan ujian bercakap ringkas dan kad kendiri untuk memastikan intensiti kekal terkawal.',
      'kesinambungan gerak, kawalan intensiti dan respons badan sendiri',
      'Buku Teks, audio, kon stesen, kad kiraan, jam randik'),
    ('flexibility','Kelenturan','kelenturan,regangan dinamik,regangan statik,regang dan tahan',
      'melaksanakan regangan dinamik atau statik pada bahagian badan yang ditetapkan dengan posisi terkawal',
      'Bingo Regangan Selamat',
      'Murid mencabut kad regangan yang terdapat dalam sumber, menunjukkan posisi secara terkawal dan menanda petak selepas pasangan menyemak bahagian badan serta jenis regangan.',
      'posisi, bahagian badan, jenis regangan dan kawalan pergerakan',
      'Buku Teks, tilam, kad regangan, papan bingo, jam randik'),
    ('muscular_fitness','Kekuatan dan Daya Tahan Otot','kekuatan otot,daya tahan otot,tekan tubi,bangkit tubi',
      'melaksanakan latihan kekuatan atau daya tahan otot dengan posisi badan dan tempoh yang ditetapkan dalam sumber',
      'Stesen Teknik Tepat',
      'Murid bergerak melalui stesen latihan Buku Teks, melaksanakan tempoh yang ditetapkan dan menerima tanda selesai apabila pasangan mengesahkan posisi serta kawalan gerakan.',
      'posisi badan, kawalan gerakan, tempoh dan pematuhan rehat',
      'Buku Teks, tilam, kon stesen, jam randik, kad semak teknik'),
    ('growth_tracking','Rekod Pertumbuhan','ketinggian,berat badan,pertumbuhan fizikal,ukur tinggi,rekod berat',
      'mengukur dan merekod data pertumbuhan kendiri menggunakan alat, unit dan kaedah yang betul tanpa membuat perbandingan tubuh',
      'Makmal Ukur dan Rekod',
      'Murid bergilir sebagai pengukur, pencatat dan penyemak alat, kemudian menyemak unit serta ketepatan rekod sendiri; data peribadi tidak dipamer atau dibandingkan.',
      'penggunaan alat, unit, ketepatan catatan dan privasi data kendiri',
      'Buku Teks, alat ukur tinggi, penimbang, lembaran rekod peribadi, pensel'),
    ('general','Kemahiran Pergerakan','kemahiran pergerakan,aktiviti fizikal,permainan kecil',
      'melaksanakan kemahiran pergerakan mengikut urutan, peralatan, ruang dan peraturan keselamatan yang dinyatakan',
      'Cabaran Tiga Percubaan',
      'Murid membuat tiga percubaan terkawal bagi kemahiran yang sama, mencatat satu pembaikan teknik dan berkongsi petunjuk keselamatan sebelum pertukaran giliran.',
      'urutan kemahiran, kawalan pergerakan dan pematuhan keselamatan',
      'Buku Teks, alatan aktiviti yang dinyatakan, kon, kad semak teknik')
), activity_rows(
  level_key, phase, suffix, row_name, pak21, is_game, priority,
  selection_weight, template
) as (
  values
    ('support','input','model_cue','Lihat–Sebut–Cuba','Demonstrate-Practise-Check',false,20,132,
      'Guru menunjukkan satu ulangan ringkas bagi %1$s. Murid menyebut dua petunjuk teknik dan satu peraturan keselamatan, kemudian meniru posisi mula tanpa melakukan keseluruhan kemahiran.'),
    ('support','guided','guided_parts','Latihan Berfasa','Peer Coaching',false,21,132,
      'Murid mencuba %1$s secara bahagian kecil pada ruang bertanda. Guru menyemak percubaan pertama, manakala pasangan menggunakan kad teknik untuk memberi satu petunjuk sebelum percubaan berikutnya.'),
    ('support','evidence','show_one_cue','Tunjuk Satu Petunjuk','Show Me',false,22,128,
      'Murid menunjukkan satu percubaan terkawal dan memilih satu bukti kejayaan: %3$s. Pasangan menyatakan bahagian yang sudah tepat dan satu pembaikan yang khusus.'),
    ('core','practice','paired_practice','Latihan Pasangan Berperanan','Cooperative Learning',false,30,136,
      'Dalam pasangan, murid bergilir sebagai pelaku dan pemerhati untuk melaksanakan %1$s. Pemerhati menanda satu petunjuk teknik, kemudian kedua-duanya bertukar peranan dan mengulang kemahiran.'),
    ('core','game','source_game','Permainan Kemahiran','Team Challenge',true,31,140,
      '%2$s Selepas pusingan, kumpulan menyemak %3$s dan menetapkan satu sasaran pembaikan untuk pusingan seterusnya.'),
    ('core','sharing','technique_huddle','Himpun Teknik','Round Robin',false,32,126,
      'Kumpulan membandingkan hasil latihan kemahiran yang sama dan memilih satu percubaan untuk diterangkan. Setiap ahli menyumbang satu pemerhatian tentang %3$s sebelum guru merumuskan teknik utama.'),
    ('challenge','practice','accuracy_decision','Ketepatan dan Keputusan','Peer Coaching',false,40,136,
      'Murid mengulang %1$s dengan sasaran ketepatan, konsistensi atau keputusan yang ditetapkan guru. Cabaran mengekalkan kemahiran, ruang dan alatan asal; murid merekod hasil setiap percubaan.'),
    ('challenge','game','decision_game','Cabaran Keputusan','Game-Based Learning',true,41,140,
      '%2$s Murid kemudian memilih satu perubahan keputusan atau strategi yang masih mematuhi teknik, ruang, alatan dan peraturan asal.'),
    ('challenge','evidence','justify_technique','Bukti Teknik','Gallery Walk',false,42,130,
      'Murid memilih satu hasil latihan sebagai bukti dan menerangkan bagaimana %3$s membantu mencapai objektif. Rakan mengemukakan satu soalan teknik, bukan menilai kemampuan fizikal murid.')
)
insert into public.rph_activity_library (
  activity_key, language_code, skill_key, phase, level_key, activity_name,
  activity_template, bbm_template, pak21, objective_keywords, source_keywords,
  year_min, year_max, is_game, priority, active, subject_key, pedagogy_key,
  activity_type, example_text, requires_source, selection_weight, subskill_key
)
select
  format('pe_y3_%s_%s', p.pattern_key, a.suffix),
  'ms', 'physical_education', a.phase, a.level_key,
  format('%s: %s', p.pattern_name, case when a.is_game then p.game_name else a.row_name end),
  format(a.template, p.technique_focus, p.game_rule, p.evidence),
  p.bbm, a.pak21,
  array[p.pattern_name, p.pattern_key]::text[],
  string_to_array(p.source_words, ','),
  3, 3, a.is_game, a.priority, true, 'pe', 'source_first_pe',
  format('pe_%s_%s', p.pattern_key, a.suffix),
  'Digunakan hanya selepas tugasan sebenar Buku Teks bagi kemahiran yang sama dikenal pasti.',
  true, a.selection_weight, p.pattern_key
from patterns p cross join activity_rows a
on conflict (activity_key) do update set
  activity_name=excluded.activity_name,
  activity_template=excluded.activity_template,
  bbm_template=excluded.bbm_template,
  pak21=excluded.pak21,
  objective_keywords=excluded.objective_keywords,
  source_keywords=excluded.source_keywords,
  activity_type=excluded.activity_type,
  example_text=excluded.example_text,
  requires_source=true,
  selection_weight=excluded.selection_weight,
  subskill_key=excluded.subskill_key,
  active=true;

with patterns(pattern_key, pattern_name, source_words, technique_focus, bbm) as (
  values
    ('balance','Imbangan','imbangan,tapak sokongan','tapak sokongan, pusat graviti dan posisi stabil','Buku Teks, tilam, kad posisi'),
    ('spring_landing','Hambur dan Pendaratan','hambur,melonjak,mendarat','tolakan, ayunan dan pendaratan terkawal','Buku Teks, tilam, kad urutan'),
    ('rotation','Putaran dan Guling','guling,putaran badan','fasa mula, putaran dan posisi akhir','Buku Teks, tilam, kad fasa'),
    ('rhythmic_movement','Pergerakan Berirama','pergerakan berirama,ikut langkah','kiraan, arah, tempo dan urutan gerak','Buku Teks, audio, kad kiraan'),
    ('invasion_game','Permainan Serangan','menghantar bola,menerima bola,mengelecek','ruang, sasaran, kawalan bola dan keputusan','Buku Teks, bola lembut, kon'),
    ('net_game','Permainan Jaring','servis,pukulan,menyangga','posisi sedia, arah dan sentuhan terkawal','Buku Teks, alatan permainan jaring, kon'),
    ('striking_fielding','Pukul dan Memadang','memukul bola,menahan bola,menangkap','kontak, tangkapan, arah dan pertukaran peranan','Buku Teks, bola lembut, bet ringan'),
    ('running','Larian','berlari,lari pecut,kelajuan','postur, ayunan tangan dan perubahan kelajuan','Buku Teks, kon, kad warna'),
    ('jumping','Lompatan','melompat,lompatan,halangan','lonjakan dan pendaratan seimbang','Buku Teks, gelung, halangan rendah'),
    ('throwing','Balingan dan Lontaran','membaling,melontar,melempar','posisi badan, arah pelepasan dan sasaran','Buku Teks, objek balingan, gelung sasaran'),
    ('traditional_game','Permainan Tradisional','tarik upih,batu seremban,karom','kemahiran, peranan dan permainan adil','Buku Teks, set permainan, kad peranan'),
    ('strategy_game','Permainan Strategi','catur,dam,strategi','gerakan sah dan sebab pemilihan','Buku Teks, papan permainan, kad situasi'),
    ('warmup_pulse','Pemanasan Badan dan Nadi','pemanasan badan,kadar nadi','urutan pemanasan dan perubahan nadi kendiri','Buku Teks, jam randik, kad urutan'),
    ('cooldown_hydration','Penyejukan Badan dan Hidrasi','penyejukan badan,hidrasi','urutan pemulihan, pernafasan dan hidrasi','Buku Teks, kad urutan, bekas air'),
    ('aerobic','Kapasiti Aerobik','aerobik,jantung dan paru','kesinambungan gerak dan kawalan intensiti','Buku Teks, audio, kon stesen'),
    ('flexibility','Kelenturan','kelenturan,regangan','jenis regangan, posisi dan bahagian badan','Buku Teks, tilam, kad regangan'),
    ('muscular_fitness','Kekuatan dan Daya Tahan Otot','kekuatan otot,daya tahan otot','posisi badan, kawalan gerakan dan tempoh','Buku Teks, tilam, jam randik'),
    ('growth_tracking','Rekod Pertumbuhan','ketinggian,berat badan,pertumbuhan','alat, unit, ketepatan dan privasi data kendiri','Buku Teks, alat ukuran, rekod peribadi'),
    ('general','Kemahiran Pergerakan','kemahiran pergerakan,aktiviti fizikal','aksi utama, alatan, ruang dan keselamatan','Buku Teks, alatan aktiviti, kad teknik')
), induction_rows(suffix, induction_type, row_name, pak21, priority, template) as (
  values
    ('visual_clue','visual','Teka Aksi','Think-Pair-Share',20,
      'Guru memaparkan satu gambar atau posisi awal daripada {{page}}. Murid meneka kemahiran, menyebut satu petunjuk berkaitan %1$s dan menyemak jangkaan dengan pasangan.'),
    ('equipment_ready','realia','Kenali Alatan dan Ruang','Round Robin',22,
      'Guru menunjukkan alatan atau penanda ruang yang digunakan dalam aktiviti pada {{page}}. Murid menerangkan fungsi satu alatan dan satu peraturan keselamatan sebelum guru membuka halaman sumber.'),
    ('technique_freeze','demonstration','Beku Teknik','Demonstrate-Practise-Check',24,
      'Guru menunjukkan satu posisi terkawal tanpa melengkapkan keseluruhan kemahiran. Murid mengenal pasti satu petunjuk %1$s, meniru posisi pada ruang sendiri dan menunggu semakan sebelum aktiviti Buku Teks dimulakan.')
)
insert into public.rph_induction_library (
  induction_key, subject_key, skill_key, language_code, induction_type,
  induction_name, induction_template, example_text, bbm_template, pak21,
  objective_keywords, source_keywords, year_min, year_max, priority,
  selection_weight, active, subskill_key
)
select
  format('pe_y3_%s_%s', p.pattern_key, i.suffix),
  'pe', 'physical_education', 'ms', i.induction_type,
  format('%s: %s', p.pattern_name, i.row_name),
  format(i.template, p.technique_focus),
  'Set induksi mengaktifkan pengetahuan sedia ada tanpa menggantikan tugasan Buku Teks.',
  p.bbm, i.pak21,
  array[p.pattern_name, p.pattern_key]::text[],
  string_to_array(p.source_words, ','),
  3, 3, i.priority, 130, true, p.pattern_key
from patterns p cross join induction_rows i
on conflict (induction_key) do update set
  induction_name=excluded.induction_name,
  induction_template=excluded.induction_template,
  example_text=excluded.example_text,
  bbm_template=excluded.bbm_template,
  pak21=excluded.pak21,
  objective_keywords=excluded.objective_keywords,
  source_keywords=excluded.source_keywords,
  selection_weight=excluded.selection_weight,
  subskill_key=excluded.subskill_key,
  active=true;

insert into public.rph_subject_pedagogy (
  subject_key, subject_name, language_code, direction, pedagogy_notes,
  preferred_methods, preferred_bbm, active
)
values (
  'pe', 'Pendidikan Jasmani', 'ms', 'ltr',
  'RPT menentukan minggu dan kemahiran; DSKP mengesahkan SK/SP; Buku Teks menentukan tugasan pergerakan, alatan dan peraturan sebenar. Semua kumpulan menjalankan kemahiran yang sama. Sokongan memecahkan kemahiran kepada bahagian kecil, kumpulan teras menjalankan tugasan asal, dan kumpulan cabaran menambah sasaran ketepatan, konsistensi atau keputusan tanpa menaikkan risiko. Permainan mini mesti mengekalkan kemahiran, ruang dan alatan sumber.',
  array['Demonstrate-Practise-Check','Peer Coaching','Skill Stations','Team Challenge','Game-Based Learning','Round Robin'],
  array['Buku Teks','alatan aktiviti yang dinyatakan','kon dan penanda ruang','kad semak teknik','kad peraturan','jam randik','lembaran rekod kendiri'],
  true
)
on conflict (subject_key) do update set
  subject_name=excluded.subject_name,
  language_code=excluded.language_code,
  direction=excluded.direction,
  pedagogy_notes=excluded.pedagogy_notes,
  preferred_methods=excluded.preferred_methods,
  preferred_bbm=excluded.preferred_bbm,
  active=true;
