-- RPH Hub: Pendidikan Jasmani Tahun 1 source-first Activity + Induction Library.
-- Source audit: RPT PJ Tahun 1 2026, DSKP KSSR PJPK Tahun 1 and PJPK Tahun 1 SK.
-- Idempotent: existing keys are updated, not duplicated.
-- Library rows wrap the real textbook task; they do not create or replace it.

with patterns(
  pattern_key, pattern_name, source_words, technique_focus,
  game_name, game_rule, evidence, bbm
) as (
  values
    ('body_awareness','Kesedaran Tubuh','kesedaran tubuh,bentuk badan,pemindahan berat badan,layangan,gerak cabaran',
      'membentuk tubuh, mengimbang, memindahkan berat badan dan melakukan layangan mengikut stesen pada Buku Teks',
      'Stesen Huruf Bergerak',
      'Kumpulan bergerak melalui stesen bentuk badan, imbangan, pemindahan berat dan layangan. Pada isyarat, murid membentuk huruf atau aksi yang ditetapkan tanpa mengganggu ruang rakan.',
      'bentuk tubuh yang jelas, tapak sokongan, pemindahan berat dan kawalan ruang',
      'Buku Teks, kad huruf atau aksi, tali lantai, gelung, kon'),
    ('space_awareness','Kesedaran Ruang','ruang diri,ruang am,batasan ruang,aras rendah,aras sederhana,aras tinggi,pulang ke rumah',
      'bergerak dalam ruang diri dan ruang am pada arah serta aras yang disebut sambil mengekalkan batas selamat',
      'Pulang ke Rumah',
      'Murid bergerak bebas pada aras yang disebut. Apabila wisel dibunyikan, murid masuk ke gelung mengikut bilangan yang ditetapkan dan membeku tanpa bersentuhan.',
      'pemilihan ruang, aras pergerakan, respons kepada isyarat dan jarak selamat',
      'Buku Teks, gelung, wisel, kad aras, kon sempadan'),
    ('direction_signal','Arah dan Isyarat','gerak isyarat,arah depan,arah belakang,kiri,kanan,atas,bawah,isyarat,tempo',
      'bergerak ke depan, belakang, kiri, kanan, atas atau bawah dan menukar arah mengikut isyarat serta tempo',
      'Kereta Api Isyarat',
      'Murid bergerak dalam barisan kecil mengikut kad arah dan bunyi alat perkusi. Ketua menukar arah hanya selepas isyarat, kemudian peranan ketua berpindah kepada murid berikutnya.',
      'arah yang tepat, perubahan arah, kawalan tempo dan komunikasi kumpulan',
      'Buku Teks, kad arah, alat perkusi, kon laluan, wisel'),
    ('pathway_speed','Laluan dan Kelajuan','laluan lurus,berlengkok,spiral,zig-zag,kawal kelajuan,tempo,irama',
      'bergerak melalui laluan lurus, berlengkok, spiral dan zig-zag sambil melaras kelajuan mengikut tempo',
      'Jejak Empat Laluan',
      'Murid memilih satu kad laluan, bergerak dari mula ke tamat dan menukar kelajuan apabila tempo berubah. Pasangan menyemak sama ada laluan dan kelajuan sepadan dengan isyarat.',
      'bentuk laluan, perubahan kelajuan, kawalan badan dan berhenti di zon tamat',
      'Buku Teks, tali atau pita laluan, kon, kad tempo, alat perkusi'),
    ('force_control','Kawalan Daya','daya ringan,daya berat,penggunaan daya,sukan rakyat,ringan dan berat',
      'membezakan dan menggunakan daya ringan atau berat mengikut objek, peranan dan aktiviti yang ditunjukkan',
      'Pilih Daya Tepat',
      'Kumpulan mencabut kad ringan atau berat lalu melaksanakan lakuan Buku Teks dengan daya yang sesuai. Rakan mengangkat kad jawapan dan memberi sebab sebelum giliran bertukar.',
      'pilihan daya yang sesuai, kawalan pergerakan dan alasan berdasarkan aktiviti',
      'Buku Teks, kad ringan dan berat, objek lembut pelbagai saiz, kon'),
    ('locomotor','Pergerakan Lokomotor','pergerakan lokomotor,berjalan,berlari,melompat,hopping,mencongklang,menggelongsor,melonjak,berskip',
      'melaksanakan berjalan, berlari, melompat sebelah kaki, mencongklang, menggelongsor, melonjak dan berskip mengikut urutan sumber',
      'Bas Henti Lokomotor',
      'Murid bergerak ke setiap hentian dan melakukan satu pergerakan lokomotor pada kad stesen. Kad hanya ditanda selepas pasangan menyebut nama gerakan dan menunjukkan arah pergerakan.',
      'jenis pergerakan, koordinasi anggota, arah dan peralihan antara stesen',
      'Buku Teks, kad stesen, kon, gelung, penanda lantai'),
    ('jump_land','Lompatan dan Pendaratan','melompat sebelah kaki,dua belah kaki,mendarat,lutut difleksi,gerak ruang',
      'melompat menggunakan sebelah atau kedua-dua kaki dan mendarat dengan kedua-dua kaki serta lutut difleksi',
      'Pulau Pendaratan',
      'Murid melompat mengikut kad kaki permulaan dan mendarat dalam gelung. Mata kumpulan diberi untuk pendaratan terkawal, bukan jarak paling jauh.',
      'kaki lonjakan, kedudukan tangan, lutut difleksi dan imbangan selepas mendarat',
      'Buku Teks, gelung, kad kaki, kon, tikar nipis'),
    ('jump_rope','Lompat Tali','lompat tali,tali diayun,ayun dan lompat,kiraan lompatan',
      'melompat melepasi tali yang diayun berulang kali mengikut irama dan giliran yang selamat',
      'Kiraan Ayunan',
      'Dua murid mengayun tali pada tempo tetap, seorang murid melompat dan seorang lagi mencatat kiraan berjaya. Semua peranan bertukar selepas masa yang ditetapkan.',
      'masa masuk, ritma lompatan, pendaratan dan pematuhan giliran',
      'Buku Teks, tali panjang, kad peranan, alat perkusi, kad kiraan'),
    ('non_locomotor','Pergerakan Bukan Lokomotor','bukan lokomotor,membongkok,mengayun,memusing,mengilas,meregang,menolak,menarik,mengimbang',
      'melakukan fleksi, ayunan, pusingan, kilasan, regangan, tolakan, tarikan dan imbangan tanpa berpindah tapak',
      'Patung Lapan Gerak',
      'Guru atau ketua menunjukkan kad aksi. Murid membentuk aksi pada ruang sendiri, membeku, kemudian pasangan menamakan gerakan dan menyemak bahawa tapak tidak berpindah.',
      'aksi bukan lokomotor yang tepat, kedudukan anggota dan kawalan ruang diri',
      'Buku Teks, kad aksi, penanda ruang, muzik atau alat perkusi'),
    ('rhythmic_movement','Pergerakan Berirama','ikut irama,pergerakan berirama,watak,muzik,tempo,lakonkan pergerakan',
      'menggabungkan gerak lokomotor atau bukan lokomotor mengikut watak, kiraan dan tempo yang ditunjukkan dalam sumber',
      'Cermin Watak Berirama',
      'Pasangan memilih satu urutan watak daripada Buku Teks. Murid pertama bergerak pada empat atau lapan kiraan dan murid kedua menjadi cermin sebelum mereka bertukar peranan.',
      'urutan gerak, tempo, ekspresi watak dan keselarasan pasangan',
      'Buku Teks, audio atau alat perkusi, kad watak, kad kiraan'),
    ('animal_movement','Penerokaan Gerak Haiwan','pergerakan haiwan,gajah,tikus,buaya,arnab,ketam,kijang,katak,beruang',
      'meniru pergerakan haiwan pada aras dan laluan berbeza sambil memindahkan berat badan dengan terkawal',
      'Safari Laluan',
      'Murid mengambil satu kad haiwan dan bergerak melalui laluan yang sepadan. Rakan meneka haiwan, aras dan cara pemindahan berat sebelum kad baharu dipilih.',
      'ciri gerak haiwan, aras, laluan, pemindahan berat dan jarak selamat',
      'Buku Teks, kad haiwan, kon, tali laluan, penanda aras'),
    ('throw_catch','Baling dan Tangkap','baling dan tangkap,balingan bawah tangan,menangkap objek,pundi kacang,gelung',
      'membaling bawah tangan atau atas kepala kepada rakan dan menangkap objek perlahan dengan posisi badan yang betul',
      'Zig-zag ke Gelung',
      'Ahli kumpulan membaling pundi kacang secara zig-zag. Murid terakhir membuat balingan bawah tangan ke gelung; semua objek dikutip hanya selepas isyarat guru.',
      'arah balingan, tangan bantuan, posisi sedia menangkap dan ketepatan gelung',
      'Buku Teks, pundi kacang, gelung, kon, kad teknik'),
    ('overarm_throw','Balingan Atas Kepala','balingan atas kepala,tangan tidak membaling,siapa kuat,baling jauh',
      'melakukan balingan atas kepala dengan tangan bantuan, langkah kaki dan pelepasan ke zon sasaran',
      'Tiga Zon Balingan',
      'Murid membaling objek lembut ke satu daripada tiga zon dan merekod zon yang dicapai. Jarak cabaran diubah melalui sasaran, bukan menggunakan objek lebih berat.',
      'tangan bantuan, langkah kaki, arah pelepasan dan pematuhan garisan',
      'Buku Teks, bola lembut atau pundi kacang, kon zon, kad rekod'),
    ('self_toss_catch','Lambung dan Tangkap','lambung dan tangkap,dilambung sendiri,kedudukan jari,kedudukan tangan',
      'melambung bola sendiri pada ketinggian terkawal dan menangkapnya dengan jari serta tangan dalam posisi sedia',
      'Lampu Isyarat Lambung',
      'Pada kad hijau murid melambung, pada kad kuning mereka menjejak bola dan pada kad merah mereka menangkap serta membeku. Pasangan menyemak posisi jari sebelum ulangan.',
      'ketinggian lambungan, tumpuan mata, posisi jari dan tangkapan terkawal',
      'Buku Teks, bola lembut pelbagai saiz, kad warna, gelung ruang'),
    ('kick_ball','Tendang dan Bergerak','tendang bola,menendang bola,kaki sokong,bola digolek,berlari ke hadapan',
      'menendang bola yang digolek menggunakan kaki yang sesuai dan terus bergerak ke hadapan untuk membantu rakan',
      'Jatuhkan Skital',
      'Seorang murid menggolek bola, rakan menendang ke arah skital lalu berlari ke zon bantuan. Pasangan bertukar peranan selepas setiap percubaan.',
      'kaki sokong di sisi bola, sentuhan kaki, arah tendangan dan gerak susulan',
      'Buku Teks, bola lembut, skital, kon zon, kad giliran'),
    ('balloon_strike','Pukul Belon','pukul belon,memukul belon,titik kontak,anggota badan,alatan pemukul',
      'memukul belon ke atas menggunakan anggota badan atau alatan ubah suai pada titik sentuh yang sesuai',
      'Belon Melepasi Tali',
      'Dua pasukan menghantar belon melepasi tali menggunakan sentuhan yang ditetapkan. Mata diberi apabila belon jatuh dalam kawasan lawan dan permainan dimulakan semula dengan tertib.',
      'titik sentuh, arah pukulan, kawalan daya dan pematuhan kawasan',
      'Buku Teks, belon, pemukul ubah suai, tali rendah, kon sempadan'),
    ('foot_dribble','Kelecek dengan Kaki','kelecek bola,lengkok skital,bahagian dalam kaki,kaki rapat dengan bola',
      'mengelecek bola menggunakan bahagian dalam kaki melalui skital secara berselang-seli',
      'Lengkok Skital',
      'Murid mengelecek dari mula hingga skital terakhir, berhenti di zon tamat dan menghantar bola kepada rakan. Skital hanya ditambah selepas kawalan bola stabil.',
      'sentuhan bahagian dalam kaki, jarak bola, laluan skital dan kawalan berhenti',
      'Buku Teks, bola, skital, kon mula dan tamat, kad semak'),
    ('hand_dribble','Kelecek dengan Tangan','kelecek tangan,bola emas,mengelecek bola satu tangan,pergerakan jari',
      'mengelecek bola berterusan menggunakan satu tangan dengan jari terkawal dalam kawasan yang ditetapkan',
      'Bola Emas Selamat',
      'Murid mengelecek dari gelung mula ke kawasan selamat sambil mengelak penanda statik. Rakan menunggu di luar laluan dan mengambil giliran selepas bola diserahkan.',
      'sentuhan jari, ketinggian lantunan, kawalan bola dan sempadan kawasan',
      'Buku Teks, bola lantun, gelung, kon, kad laluan'),
    ('balance','Imbangan','imbangan sebelah kaki,tapak sokongan,kestabilan,pusat graviti',
      'melakukan imbangan sebelah kaki atau menggunakan satu hingga empat tapak sokongan dengan posisi stabil',
      'Patung Tapak Sokongan',
      'Murid mencabut kad bilangan tapak sokongan, membentuk imbangan dan membeku pada kiraan yang sesuai. Pasangan menyebut tapak sokongan dan satu sebab posisi itu stabil.',
      'bilangan tapak sokongan, kedudukan tangan, pusat graviti dan posisi akhir',
      'Buku Teks, tikar, kad tapak sokongan, kon, kad semak'),
    ('rotation','Putaran dan Guling','putaran menegak,guling balak,guling sisi,guling depan,posisi tuck,tenggiling',
      'melakukan putaran atau guling mengikut fasa mula, bentuk badan bulat dan posisi akhir di atas tilam',
      'Puzzle Fasa Guling',
      'Dengan pengawasan guru, murid melakukan kemahiran pada tilam. Pasangan kemudian menyusun kad mula, putaran dan akhir sebelum percubaan seterusnya.',
      'urutan fasa, bentuk badan, arah putaran dan posisi akhir terkawal',
      'Buku Teks, tilam gimnastik, kad fasa, penanda ruang'),
    ('aquatic_confidence','Keselamatan dan Keyakinan Air','kolam renang,bobbing,apungan tiarap,luncur,berjalan dalam air,masuk air',
      'mematuhi peraturan kolam dan melakukan kemahiran masuk air, berdiri, berjalan, bobbing, apungan tiarap serta luncur mengikut arahan',
      'Kad Urutan Akuatik',
      'Di bawah pengawasan guru yang bertanggungjawab dan di ruang air yang sesuai, murid melaksanakan hanya kemahiran yang ditetapkan. Rakan di luar giliran menyusun kad urutan dan menyebut peraturan keselamatan.',
      'pematuhan arahan, urutan kemahiran, kawalan pernafasan dan tindakan selamat',
      'Buku Teks, kad peraturan, kad urutan, alat apungan yang diluluskan sekolah'),
    ('traditional_game','Permainan Tradisional','datuk harimau,congkak,permainan tradisional,santai petang',
      'menggunakan kemahiran lokomotor atau manipulasi dan mematuhi peraturan permainan Datuk Harimau atau Congkak',
      'Pusingan Warisan',
      'Kumpulan memainkan satu pusingan mengikut peraturan Buku Teks. Murid bergilir sebagai pemain, penjaga giliran dan pencatat sebelum permainan disambung.',
      'pemahaman peraturan, kemahiran permainan, giliran, kerjasama dan permainan adil',
      'Buku Teks, set congkak atau penanda permainan, kad peranan, papan skor'),
    ('creative_build','Reka dan Bina','istana pasir,plastisin,blok mainan,mereka cipta objek,saya kreatif',
      'membina istana atau objek menggunakan bahan yang ditetapkan dan menerangkan sebab bagi bentuk yang dipilih',
      'Arkitek Cilik',
      'Kumpulan menerima kad ciri seperti pintu, menara atau bumbung, kemudian membina objek menggunakan bahan yang dipilih. Setiap ahli menerangkan satu bahagian sebelum galeri mini.',
      'kestabilan binaan, penggunaan bahan, ciri reka bentuk dan penerangan mudah',
      'Buku Teks, pasir bersih atau plastisin atau blok mainan, kad ciri, alas kerja'),
    ('warmup_pulse','Pemanasan Badan dan Nadi','memanaskan badan,pemanasan badan,kadar nadi,denyutan nadi,suhu badan,kadar pernafasan',
      'melakukan urutan berjalan, berlari dan regangan serta mengenal pasti perubahan suhu, pernafasan dan nadi',
      'Detektif Respons Badan',
      'Murid mengikuti urutan pemanasan Buku Teks, berhenti pada isyarat dan memilih kad suhu, pernafasan atau nadi yang menerangkan perubahan pada diri sendiri.',
      'urutan pemanasan, kawalan intensiti dan penerangan respons badan sendiri',
      'Buku Teks, kad urutan, kad respons badan, jam randik, bekas air'),
    ('cooldown_hydration','Penyejukan Badan dan Hidrasi','menyejukkan badan,penyejukan badan,minum air,hidrasi,kadar nadi menurun',
      'melakukan penyejukan badan dan memilih masa pengambilan air sebelum, semasa serta selepas aktiviti',
      'Susun Rutin Pulih',
      'Kumpulan menyusun kad berjalan perlahan, regangan terkawal, pernafasan dan minum air. Selepas guru menyemak urutan, murid melaksanakannya pada kadar selamat.',
      'urutan penyejukan, pernafasan terkawal, perubahan nadi dan pilihan hidrasi',
      'Buku Teks, kad urutan, jam randik, bekas air murid'),
    ('aerobic','Kapasiti Aerobik','kapasiti aerobik,jantung,paru-paru,berlari,turun naik bangku,skip,papan roda,tarian aerobik',
      'melakukan aktiviti berterusan yang dipilih daripada sumber dan mengaitkan fungsi jantung serta paru-paru',
      'Litar Jantung Cergas',
      'Kumpulan bergerak melalui stesen berlari, skip, turun naik bangku rendah atau gerak aerobik yang sesuai. Murid mengekalkan tempo yang ditetapkan dan berehat mengikut isyarat.',
      'kesinambungan gerak, kawalan tempo, pematuhan rehat dan penerangan fungsi jantung',
      'Buku Teks, kon stesen, bangku rendah yang stabil, audio, jam randik'),
    ('flexibility','Kelenturan','regangan dinamik,regangan statik,kelenturan,siap siaga,tenang-tenang',
      'melakukan regangan dinamik atau statik pada bahagian badan yang ditunjukkan dengan pergerakan terkawal',
      'Bingo Regangan Selamat',
      'Murid mencabut kad regangan Buku Teks, menunjukkan lakuan pada kedua-dua belah badan dan menanda petak selepas pasangan mengenal pasti bahagian yang diregang.',
      'jenis regangan, bahagian badan, posisi, kawalan gerakan dan larangan menghenjut',
      'Buku Teks, kad regangan, tikar, papan bingo, jam randik'),
    ('muscular_fitness','Kekuatan dan Daya Tahan Otot','kekuatan otot,daya tahan otot,tekan tubi,cangkung separa,ringkuk tubi,bergayut,meniti palang',
      'melakukan senaman kekuatan atau daya tahan otot mengikut posisi, masa dan rehat yang ditetapkan dalam sumber',
      'Stesen Teknik Tepat',
      'Murid bergerak melalui stesen yang dipilih guru, melakukan lakuan mengikut kemampuan dan berhenti pada isyarat. Pasangan hanya menyemak posisi serta masa, bukan membandingkan prestasi.',
      'posisi badan, kawalan gerakan, masa lakuan, pernafasan dan pematuhan rehat',
      'Buku Teks, tikar, kon stesen, jam randik, kad semak teknik'),
    ('core_stability','Kestabilan Otot Teras','otot teras,core muscle,mengempis abdomen,angkat badan sisi,tekan tubi bersiku',
      'melakukan senaman otot teras yang ditetapkan dengan penjajaran badan, pernafasan dan tempoh terkawal',
      'Enam Kad Teras',
      'Murid memilih satu kad senaman teras daripada Buku Teks, melakukan lakuan mengikut kemampuan dan menunjukkan bahagian otot yang terlibat pada rajah sebelum bertukar kad.',
      'posisi mula, penjajaran badan, kawalan pernafasan dan pengenalpastian otot teras',
      'Buku Teks, tikar, kad senaman, rajah otot, jam randik'),
    ('growth_tracking','Ukur dan Rekod Pertumbuhan','mengukur tinggi,menimbang berat,ketinggian,berat badan,jadual rekod',
      'menggunakan alat serta unit yang betul untuk mengukur dan merekod tinggi serta berat diri secara peribadi',
      'Makmal Ukur dan Rekod',
      'Murid bergilir sebagai pengukur, pencatat dan penyemak alat. Setiap murid menyemak rekod sendiri; data tidak dipamerkan, dibandingkan atau dijadikan pertandingan.',
      'penggunaan alat, unit meter dan kilogram, ketepatan catatan dan privasi data',
      'Buku Teks, alat ukur tinggi, penimbang, lembaran rekod peribadi, pensel')
), activity_rows(
  level_key, phase, suffix, row_name, pak21, is_game, priority,
  selection_weight, template
) as (
  values
    ('support','input','picture_cue','Lihat dan Kenal Aksi','Think-Pair-Share',false,20,134,
      'Guru membuka gambar atau urutan pada {{page}} dan menunjukkan satu contoh bagi %1$s. Murid menamakan aksi, alatan dan satu peraturan keselamatan sebelum meniru posisi mula.'),
    ('support','guided','guided_turn','Cuba dengan Petunjuk','Demonstrate-Practise-Check',false,21,136,
      'Murid melaksanakan %1$s secara bahagian kecil pada ruang bertanda. Guru menyemak percubaan pertama dan pasangan menggunakan kad petunjuk sebelum percubaan kedua.'),
    ('support','evidence','show_and_name','Tunjuk dan Sebut','Show Me',false,22,130,
      'Selepas tugasan Buku Teks pada {{page}}, murid menunjukkan satu percubaan terkawal dan menyebut satu bukti kejayaan: %3$s. Pasangan memberi satu petunjuk pembaikan.'),
    ('core','practice','paired_roles','Pasangan Pelaku-Pemerhati','Cooperative Learning',false,30,138,
      'Murid bergilir sebagai pelaku dan pemerhati untuk melaksanakan %1$s berdasarkan urutan pada {{page}}. Pemerhati menanda satu petunjuk, kemudian peranan bertukar.'),
    ('core','game','source_game','Permainan Kemahiran Buku','Game-Based Learning',true,31,142,
      '%2$s Selepas pusingan, kumpulan menyemak %3$s dan menetapkan satu sasaran pembaikan yang masih menggunakan kemahiran serta alatan asal.'),
    ('core','sharing','two_cues','Dua Petunjuk Teknik','Round Robin',false,32,128,
      'Setiap ahli menyatakan satu pemerhatian tentang %3$s daripada tugasan pada {{page}}. Kumpulan memilih dua petunjuk teknik untuk diuji semula pada percubaan berikutnya.'),
    ('challenge','practice','accuracy_target','Sasaran Ketepatan','Peer Coaching',false,40,138,
      'Murid mengulang %1$s dengan sasaran ketepatan atau konsistensi yang sesuai. Kemahiran, ruang dan alatan Buku Teks dikekalkan; murid merekod hasil sendiri.'),
    ('challenge','game','decision_round','Pusingan Keputusan','Team Challenge',true,41,142,
      '%2$s Murid memilih satu keputusan atau strategi bagi pusingan seterusnya tanpa menambah risiko, ketinggian, beban atau alatan yang tidak terdapat dalam sumber.'),
    ('challenge','evidence','explain_cue','Jelaskan Bukti Teknik','Gallery Walk',false,42,132,
      'Murid memilih satu hasil daripada tugasan pada {{page}} dan menerangkan bagaimana %3$s membantu mencapai objektif. Rakan bertanya satu soalan teknik yang khusus.')
)
insert into public.rph_activity_library (
  activity_key, language_code, skill_key, phase, level_key, activity_name,
  activity_template, bbm_template, pak21, objective_keywords, source_keywords,
  year_min, year_max, is_game, priority, active, subject_key, pedagogy_key,
  activity_type, example_text, requires_source, selection_weight, subskill_key
)
select
  format('pe_y1_%s_%s', p.pattern_key, a.suffix),
  'ms', 'physical_education', a.phase, a.level_key,
  format('%s: %s', p.pattern_name, case when a.is_game then p.game_name else a.row_name end),
  format(a.template, p.technique_focus, p.game_rule, p.evidence),
  p.bbm, a.pak21,
  array[p.pattern_name, p.pattern_key]::text[],
  string_to_array(p.source_words, ','),
  1, 1, a.is_game, a.priority, true, 'pe', 'source_first_pe',
  format('pe_y1_%s_%s', p.pattern_key, a.suffix),
  'Digunakan hanya selepas tugasan sebenar Buku Teks bagi kemahiran dan halaman yang sama dikenal pasti.',
  true, a.selection_weight, p.pattern_key
from patterns p cross join activity_rows a
on conflict (activity_key) do update set
  activity_name=excluded.activity_name,
  activity_template=excluded.activity_template,
  bbm_template=excluded.bbm_template,
  pak21=excluded.pak21,
  objective_keywords=excluded.objective_keywords,
  source_keywords=excluded.source_keywords,
  activity_type=excluded.activity_type,
  example_text=excluded.example_text,
  requires_source=true,
  selection_weight=excluded.selection_weight,
  subskill_key=excluded.subskill_key,
  active=true;

with patterns(pattern_key, pattern_name, source_words, technique_focus, bbm) as (
  values
    ('body_awareness','Kesedaran Tubuh','kesedaran tubuh,bentuk badan,pemindahan berat,layangan','bentuk tubuh, tapak sokongan dan pemindahan berat','Buku Teks, kad aksi, gelung, kon'),
    ('space_awareness','Kesedaran Ruang','ruang diri,ruang am,batasan ruang,aras','ruang diri, ruang am, aras dan jarak selamat','Buku Teks, gelung, kad aras, kon'),
    ('direction_signal','Arah dan Isyarat','arah depan,belakang,kiri,kanan,atas,bawah,isyarat','arah, perubahan arah, isyarat dan tempo','Buku Teks, kad arah, alat perkusi, kon'),
    ('pathway_speed','Laluan dan Kelajuan','lurus,berlengkok,spiral,zig-zag,kelajuan','bentuk laluan dan perubahan kelajuan','Buku Teks, tali laluan, kon, kad tempo'),
    ('force_control','Kawalan Daya','daya ringan,daya berat,sukan rakyat','pemilihan daya ringan atau berat','Buku Teks, kad daya, objek lembut, kon'),
    ('locomotor','Pergerakan Lokomotor','berjalan,berlari,melompat,mencongklang,menggelongsor,berskip','jenis gerak lokomotor dan koordinasi anggota','Buku Teks, kad stesen, kon, gelung'),
    ('jump_land','Lompatan dan Pendaratan','melompat,mendarat,lutut difleksi','lonjakan, posisi lutut dan pendaratan','Buku Teks, gelung, kad kaki, tikar'),
    ('jump_rope','Lompat Tali','lompat tali,tali diayun,kiraan','masa masuk, ritma dan pendaratan','Buku Teks, tali, kad peranan, kad kiraan'),
    ('non_locomotor','Pergerakan Bukan Lokomotor','membongkok,mengayun,memusing,mengilas,meregang,menolak,menarik','aksi tanpa berpindah tapak dan kawalan ruang','Buku Teks, kad aksi, penanda ruang'),
    ('rhythmic_movement','Pergerakan Berirama','ikut irama,watak,muzik,tempo','urutan gerak, tempo dan ekspresi watak','Buku Teks, audio, kad watak, kad kiraan'),
    ('animal_movement','Penerokaan Gerak Haiwan','gajah,tikus,buaya,arnab,ketam,kijang,katak,beruang','ciri gerak haiwan, aras dan pemindahan berat','Buku Teks, kad haiwan, kon, tali laluan'),
    ('throw_catch','Baling dan Tangkap','baling bawah tangan,tangkap,pundi kacang,gelung','arah balingan dan posisi sedia menangkap','Buku Teks, pundi kacang, gelung, kon'),
    ('overarm_throw','Balingan Atas Kepala','balingan atas kepala,tangan tidak membaling','tangan bantuan, langkah kaki dan pelepasan','Buku Teks, bola lembut, kon zon, kad rekod'),
    ('self_toss_catch','Lambung dan Tangkap','lambung,tangkap,kedudukan jari','ketinggian lambungan, tumpuan mata dan posisi jari','Buku Teks, bola lembut, kad warna, gelung'),
    ('kick_ball','Tendang dan Bergerak','tendang bola,kaki sokong,bola digolek','kaki sokong, arah tendangan dan gerak susulan','Buku Teks, bola lembut, skital, kon'),
    ('balloon_strike','Pukul Belon','pukul belon,titik kontak,alatan pemukul','titik sentuh, arah pukulan dan kawalan daya','Buku Teks, belon, pemukul ubah suai, tali'),
    ('foot_dribble','Kelecek dengan Kaki','kelecek bola,bahagian dalam kaki,lengkok skital','sentuhan kaki, jarak bola dan laluan skital','Buku Teks, bola, skital, kon'),
    ('hand_dribble','Kelecek dengan Tangan','kelecek tangan,bola emas,pergerakan jari','sentuhan jari, ketinggian lantunan dan sempadan','Buku Teks, bola lantun, gelung, kon'),
    ('balance','Imbangan','imbangan,tapak sokongan,kestabilan','tapak sokongan, pusat graviti dan posisi stabil','Buku Teks, tikar, kad imbangan, kon'),
    ('rotation','Putaran dan Guling','putaran,guling,tuck,tenggiling','fasa mula, bentuk badan dan posisi akhir','Buku Teks, tilam, kad fasa, penanda ruang'),
    ('aquatic_confidence','Keselamatan dan Keyakinan Air','kolam renang,bobbing,apungan,luncur','peraturan kolam, urutan kemahiran dan kawalan pernafasan','Buku Teks, kad peraturan, kad urutan, alat apungan sekolah'),
    ('traditional_game','Permainan Tradisional','datuk harimau,congkak,permainan tradisional','peraturan, giliran, kerjasama dan permainan adil','Buku Teks, set permainan, kad peranan'),
    ('creative_build','Reka dan Bina','istana pasir,plastisin,blok mainan','kestabilan, bahan dan ciri reka bentuk','Buku Teks, bahan binaan, kad ciri, alas kerja'),
    ('warmup_pulse','Pemanasan Badan dan Nadi','memanaskan badan,kadar nadi,suhu badan,pernafasan','urutan pemanasan dan perubahan respons badan','Buku Teks, kad urutan, jam randik, bekas air'),
    ('cooldown_hydration','Penyejukan Badan dan Hidrasi','menyejukkan badan,minum air,hidrasi','urutan pulih, pernafasan dan hidrasi','Buku Teks, kad urutan, jam randik, bekas air'),
    ('aerobic','Kapasiti Aerobik','jantung,paru-paru,berlari,skip,aerobik','kesinambungan gerak, tempo dan fungsi jantung','Buku Teks, kon stesen, audio, jam randik'),
    ('flexibility','Kelenturan','regangan dinamik,regangan statik,kelenturan','jenis regangan, bahagian badan dan kawalan','Buku Teks, kad regangan, tikar, jam randik'),
    ('muscular_fitness','Kekuatan dan Daya Tahan Otot','tekan tubi,cangkung,ringkuk tubi,bergayut','posisi badan, masa, pernafasan dan rehat','Buku Teks, tikar, kon stesen, jam randik'),
    ('core_stability','Kestabilan Otot Teras','otot teras,core muscle,abdomen','penjajaran badan, pernafasan dan otot teras','Buku Teks, tikar, kad senaman, rajah otot'),
    ('growth_tracking','Ukur dan Rekod Pertumbuhan','ukur tinggi,timbang berat,jadual rekod','alat, unit, ketepatan dan privasi data','Buku Teks, alat ukur, penimbang, rekod peribadi')
), induction_rows(suffix, induction_type, row_name, pak21, priority, template) as (
  values
    ('visual_clue','visual','Teka Aksi Buku','Think-Pair-Share',20,
      'Guru memaparkan satu gambar daripada {{page}}. Murid meneka aksi, menyebut satu petunjuk berkaitan %1$s dan menyemak jawapan bersama pasangan.'),
    ('equipment_ready','realia','Kenali Alatan dan Ruang','Round Robin',22,
      'Guru menunjukkan alatan atau penanda ruang yang digunakan pada {{page}}. Murid menerangkan fungsi satu alatan dan satu peraturan keselamatan sebelum aktiviti bermula.'),
    ('technique_freeze','demonstration','Beku Posisi Mula','Demonstrate-Practise-Check',24,
      'Guru menunjukkan satu posisi mula tanpa melengkapkan keseluruhan kemahiran. Murid mengenal pasti %1$s, meniru posisi pada ruang sendiri dan menunggu semakan guru.')
)
insert into public.rph_induction_library (
  induction_key, subject_key, skill_key, language_code, induction_type,
  induction_name, induction_template, example_text, bbm_template, pak21,
  objective_keywords, source_keywords, year_min, year_max, priority,
  selection_weight, active, subskill_key
)
select
  format('pe_y1_%s_%s', p.pattern_key, i.suffix),
  'pe', 'physical_education', 'ms', i.induction_type,
  format('%s: %s', p.pattern_name, i.row_name),
  format(i.template, p.technique_focus),
  'Set induksi mengaktifkan pengetahuan sedia ada tanpa menggantikan tugasan Buku Teks.',
  p.bbm, i.pak21,
  array[p.pattern_name, p.pattern_key]::text[],
  string_to_array(p.source_words, ','),
  1, 1, i.priority, 132, true, p.pattern_key
from patterns p cross join induction_rows i
on conflict (induction_key) do update set
  induction_name=excluded.induction_name,
  induction_template=excluded.induction_template,
  example_text=excluded.example_text,
  bbm_template=excluded.bbm_template,
  pak21=excluded.pak21,
  objective_keywords=excluded.objective_keywords,
  source_keywords=excluded.source_keywords,
  selection_weight=excluded.selection_weight,
  subskill_key=excluded.subskill_key,
  active=true;
