-- RPH Hub: Pendidikan Kesihatan Tahun 1 source-first Activity + Induction Library.
-- Source audit: RPT PK Tahun 1 2026, DSKP KSSR PJPK Tahun 1 and PJPK Tahun 1 SK.
-- Idempotent: existing keys are updated, not duplicated.
-- Library rows wrap the verified textbook task and never replace it.

with patterns(
  pattern_key, pattern_name, source_words, source_task,
  game_name, game_rule, evidence, bbm
) as (
  values
    ('body_knowledge','Kenali Anggota Tubuh',
      'anggota tubuh,bahagian tubuh,rambut,mata,telinga,hidung,mulut,deria',
      'meneliti rajah anggota tubuh pada Buku Teks, menamakan anggota yang ditunjukkan dan memadankannya dengan fungsi atau deria yang sesuai',
      'Kad Deria Tepat',
      'Kumpulan mencabut satu kad aktiviti seperti mendengar, membaca, menghidu atau mengunyah, kemudian memilih kad anggota tubuh yang sesuai dan menunjukkan bukti pada rajah Buku Teks.',
      'nama anggota tubuh, fungsi atau deria dan padanan yang tepat',
      'Buku Teks, kad anggota tubuh, kad fungsi deria, papan padanan'),
    ('personal_hygiene','Kebersihan Fizikal dan Alatan Diri',
      'kebersihan fizikal,mandi,cuci tangan,potong kuku,pakaian bersih,alatan keperluan diri,tidak boleh dikongsi',
      'meneliti gambar amalan kebersihan, menyusun rutin mandi, mencuci selepas ke tandas, mengelap badan, memakai pakaian bersih dan memotong kuku serta mengenal pasti alatan diri yang tidak boleh dikongsi',
      'Beg Kebersihan Bijak',
      'Kumpulan memilih kad amalan atau alatan daripada beg misteri. Kad amalan disusun mengikut rutin, manakala kad alatan diletakkan pada ruang “boleh dikongsi” atau “kegunaan sendiri” sebelum alasan disemak pada Buku Teks.',
      'urutan amalan, pilihan alatan diri dan sebab menjaga kebersihan',
      'Buku Teks, beg misteri, kad rutin kebersihan, kad alatan diri, papan kategori'),
    ('personal_boundaries','Sentuhan Selamat dan Batas Tubuh',
      'sentuhan selamat,sentuhan tidak selamat,sentuhan tidak selesa,jangan sentuh,berkata tidak,anggota tubuh',
      'meneliti situasi bergambar, membezakan sentuhan selamat, tidak selamat atau tidak selesa dan menyusun tindakan berkata TIDAK, beredar serta memberitahu orang dewasa yang dipercayai',
      'Lampu Isyarat Selamat',
      'Guru membaca situasi rekaan tanpa lakonan sentuhan. Kumpulan mengangkat kad hijau, kuning atau merah, kemudian memilih kad tindakan TIDAK, BEREDAR atau BERITAHU. Murid tidak diminta menceritakan pengalaman sendiri.',
      'pengelasan situasi, ayat penolakan yang jelas dan urutan mendapatkan bantuan',
      'Buku Teks, kad situasi rekaan, kad hijau-kuning-merah, kad tindakan selamat'),
    ('medicine_safety','Ubat Digunakan dengan Betul dan Selamat',
      'ubat,preskripsi doktor,ahli farmasi,tarikh luput,ubat orang lain,penyimpanan ubat,label ubat',
      'mengikuti cerita bergambar tentang pemilihan ubat, membaca maklumat asas pada label, menerangkan sebab mematuhi arahan doktor atau ahli farmasi serta memilih tempat penyimpanan yang betul',
      'Detektif Label Ubat',
      'Kumpulan menggunakan kad label rekaan untuk mencari nama ubat, sukatan, kekerapan dan waktu pengambilan. Mereka kemudian menolak kad ubat tamat tempoh, ubat orang lain atau tempat simpanan yang tidak selamat. Tiada ubat sebenar digunakan.',
      'maklumat label, sebab penggunaan betul dan pilihan penyimpanan selamat',
      'Buku Teks, kad label ubat rekaan, kad tempat simpanan, papan betul-tidak betul'),
    ('emotion_identification','Kenali Pelbagai Emosi',
      'pelbagai emosi,gembira,sedih,takut,marah,malu,teka-teki emosi,ekspresi',
      'meneliti ekspresi dan situasi pada Buku Teks, menamakan emosi gembira, sedih, takut, marah atau malu serta menyatakan petunjuk yang membantu mengenal pasti emosi',
      'Teka Ekspresi',
      'Seorang murid mengambil kad situasi rekaan dan menunjukkan ekspresi muka atau memilih kad emoji tanpa mendedahkan pengalaman peribadi. Kumpulan meneka emosi dan menyebut petunjuk daripada kad atau halaman sumber.',
      'nama emosi, petunjuk ekspresi atau situasi dan alasan yang munasabah',
      'Buku Teks, kad emosi, kad situasi rekaan, kad emoji, papan jawapan'),
    ('needs_wants','Keperluan dan Kehendak',
      'keperluan,kehendak,barang keperluan,barang yang ingin dimiliki,membeli-belah',
      'meneliti situasi membeli-belah pada Buku Teks, mengelaskan barang kepada keperluan atau kehendak dan memberikan alasan berdasarkan kegunaan dalam kehidupan harian',
      'Troli Pilihan Bijak',
      'Kumpulan menerima kad barang dan dua bakul bertanda KEPERLUAN serta KEHENDAK. Setiap kad hanya boleh dimasukkan selepas murid memberikan satu alasan yang berkaitan dengan kegunaan barang.',
      'pengelasan barang, alasan kegunaan dan keputusan yang sesuai',
      'Buku Teks, kad barang, dua bakul kategori, kad alasan, penanda kumpulan'),
    ('emotion_management','Luah dan Urus Emosi',
      'meluahkan emosi,mengurus emosi,jaga emosi,sabar,keperluan dan kehendak',
      'membandingkan dua respons dalam situasi Buku Teks, memilih cara meluahkan perasaan dengan sopan dan menyusun tindakan menenangkan diri sebelum membuat keputusan',
      'Tangga Tenang',
      'Kumpulan menyusun kad BERHENTI, TARIK NAFAS, SEBUT PERASAAN, PILIH TINDAKAN dan BERCAKAP SOPAN bagi situasi rekaan. Mereka menerangkan mengapa susunan itu membantu mengurus emosi.',
      'nama emosi, ayat luahan yang sesuai dan urutan mengurus emosi',
      'Buku Teks, kad Tangga Tenang, kad dialog rekaan, papan urutan'),
    ('family_roles','Peranan Diri, Keluarga dan Penjaga',
      'peranan ahli keluarga,peranan penjaga,keluarga angkat,peranan di rumah,bantu pak cik',
      'meneliti gambar keluarga atau penjaga pada Buku Teks, mengenal pasti peranan setiap watak dan memadankan tindakan membantu dengan tanggungjawab yang sesuai',
      'Roda Peranan Keluarga',
      'Murid memutar roda watak rekaan, mencabut satu kad tugasan rumah dan menentukan sama ada padanan itu sesuai. Kumpulan membetulkan padanan dengan merujuk gambar serta dialog pada Buku Teks.',
      'watak, peranan, tindakan membantu dan alasan padanan',
      'Buku Teks, roda watak, kad tugasan rumah, papan padanan, kad dialog'),
    ('family_uniqueness','Keistimewaan Diri dan Keluarga',
      'keistimewaan diri,keistimewaan keluarga,hobi,kebolehan,minat,keluarga saya',
      'meneliti gambar hobi, minat dan kebolehan keluarga dalam Buku Teks lalu menyatakan keistimewaan watak menggunakan ayat positif yang menghormati perbezaan',
      'Bingo Bakat dan Minat',
      'Kumpulan menerima papan bingo hobi, minat dan kebolehan. Guru membaca petunjuk watak daripada halaman sumber; murid menanda petak yang sesuai dan membina satu ayat positif tentang watak itu.',
      'hobi atau kebolehan, ayat positif dan sikap menghormati perbezaan',
      'Buku Teks, kad hobi dan kebolehan, papan bingo, penanda'),
    ('family_respect','Hormat dan Bantu-membantu',
      'hormat keluarga,bantu-membantu,adab di rumah,komunikasi keluarga,terima kasih,sila,tolong',
      'mengikuti dialog keluarga pada Buku Teks, mengenal pasti ungkapan sopan dan melengkapkan situasi bantu-membantu atau tugasan rumah dengan dialog yang sesuai',
      'Dialog Sopan Bersambung',
      'Pasangan mencantumkan kad dialog seperti SILA, TOLONG, TERIMA KASIH dan BAIK dengan situasi rumah rekaan. Mereka membaca dialog dan menyemak sama ada bahasa serta tindakan menunjukkan hormat.',
      'ungkapan sopan, tindakan membantu dan komunikasi yang menghormati',
      'Buku Teks, kad dialog, kad situasi rumah, papan cantuman'),
    ('healthy_relationships','Hubungan Sihat dan Etika Perhubungan',
      'hubungan yang sihat,etika perhubungan,ibu bapa,penjaga,rakan sebaya,jiran,hormat-menghormati',
      'meneliti contoh hubungan dalam Buku Teks, memadankan ibu bapa, penjaga, keluarga, rakan atau jiran dengan etika perhubungan dan menerangkan kepentingannya',
      'Jambatan Hubungan Sihat',
      'Kumpulan membina jambatan kad daripada WATAK kepada ETIKA seperti memberi salam, mendengar, meminta izin atau membantu. Setiap sambungan perlu disertai satu sebab sebelum kad seterusnya diletakkan.',
      'jenis hubungan, etika yang sesuai dan sebab hubungan itu penting',
      'Buku Teks, kad watak, kad etika, papan jambatan, kad sebab'),
    ('relationship_refusal','Berkata TIDAK dan Mendapatkan Bantuan',
      'jangan sentuh saya,berkata tidak,berlari ke tempat selamat,menjerit,minta pertolongan,batas perhubungan',
      'meneliti tindakan keselamatan pada Buku Teks dan menyusun ayat tegas, beredar ke tempat selamat, meminta pertolongan serta memberitahu orang dewasa yang dipercayai',
      'Tiga Pintu Selamat',
      'Kumpulan menyelesaikan situasi rekaan dengan memilih tiga pintu secara urutan: KATAKAN TIDAK, BEREDAR dan BERITAHU. Tiada sentuhan dilakonkan dan murid tidak diminta menceritakan pengalaman sendiri.',
      'ayat tegas, tempat selamat dan orang dewasa yang sesuai untuk membantu',
      'Buku Teks, kad situasi rekaan, kad tiga pintu, kad orang dewasa dipercayai'),
    ('germ_spread','Kuman dan Cara Merebak',
      'maksud kuman,kuman merebak,sentuhan,udara,makanan kotor,minuman kotor,kuman oh kuman',
      'membaca dialog Buku Teks tentang maksud kuman, mengenal pasti penyebaran melalui sentuhan, udara, makanan atau minuman tercemar dan melakonkan dialog sumber secara berkumpulan',
      'Jejak Laluan Kuman',
      'Kumpulan mengikuti anak panah daripada kad KUMAN kepada kad SENTUHAN, UDARA, MAKANAN atau MINUMAN. Pada setiap laluan, murid memilih satu tindakan yang boleh memutuskan penyebaran.',
      'maksud kuman, cara merebak dan tindakan memutuskan penyebaran',
      'Buku Teks, kad dialog, kad laluan kuman, anak panah, kad tindakan'),
    ('germ_disease','Penyakit Bawaan Kuman',
      'penyakit bawaan kuman,batuk,bersin,penyakit kulit,cirit-birit,jejak kuman',
      'menyelesaikan teka-teki atau gambar penyakit dalam Buku Teks, memadankan petunjuk umum dengan nama penyakit dan mengaitkannya dengan amalan kebersihan',
      'Detektif Petunjuk Penyakit',
      'Guru membaca petunjuk rekaan berasaskan Buku Teks. Kumpulan memilih kad penyakit, menggariskan kata petunjuk dan memasangkan satu kad amalan kebersihan yang sesuai.',
      'nama penyakit, kata petunjuk dan amalan pencegahan yang sepadan',
      'Buku Teks, kad petunjuk, kad penyakit, kad amalan kebersihan, pen penanda'),
    ('disease_prevention','Cegah Penyakit melalui Kebersihan',
      'mencegah penyakit,elak penyakit,cuci tangan,tutup mulut,batuk,bersin,sapu tangan,mandi setiap hari',
      'meneliti gambar amalan kebersihan pada Buku Teks, melakonkan urutan mencuci tangan atau etika batuk dan bersin serta menerangkan bagaimana amalan itu membantu mencegah penyakit',
      'Perisai Kebersihan',
      'Kumpulan memilih kad ancaman kuman dan membina perisai menggunakan kad CUCI TANGAN, TUTUP MULUT, GUNA SAPU TANGAN atau MANDI. Mata diberi apabila tindakan dan sebab sepadan.',
      'demonstrasi amalan, urutan tindakan dan sebab pencegahan',
      'Buku Teks, kad amalan, kad ancaman kuman, papan perisai, bahan demonstrasi bersih'),
    ('environmental_safety','Bijak dalam Situasi Tidak Selamat',
      'situasi tidak selamat,pencuri,orang tidak dikenali,diikuti,tempat awam,telefon polis,beritahu guru',
      'meneliti situasi bergambar di rumah, sekolah, taman permainan atau tempat awam, mengenal pasti petunjuk bahaya dan memilih tindakan beredar, meminta bantuan atau menghubungi pihak yang sesuai',
      'Pilih Laluan Selamat',
      'Kumpulan menggerakkan watak pada peta situasi rekaan. Pada setiap simpang, murid memilih laluan ke tempat selamat atau orang dewasa yang boleh membantu dan menerangkan petunjuk bahaya.',
      'petunjuk situasi tidak selamat, pilihan tindakan dan sumber bantuan',
      'Buku Teks, peta situasi rekaan, kad tindakan, kad bantuan, penanda watak'),
    ('bullying_prevention','Kenali Buli dan Elakkan Buli',
      'buli,pembuli,mangsa buli,dibuli,jangan ganggu saya,maklumi guru,beritahu ibu bapa',
      'meneliti kesan buli dan kad tindakan Buku Teks, mengenal pasti perlakuan buli serta menyusun tindakan berkata TIDAK, beredar dan memaklumkan guru atau penjaga',
      'Perisai Anti-Buli',
      'Guru membaca situasi buli rekaan tanpa meminta pengalaman murid. Kumpulan mengangkat kad HENTIKAN, BEREDAR atau BERITAHU, kemudian membina satu ayat tegas dan memilih orang dewasa yang boleh membantu.',
      'pengenalpastian buli, ayat tegas dan tindakan mendapatkan bantuan',
      'Buku Teks, kad situasi rekaan, kad tindakan, kad orang dewasa, papan perisai'),
    ('nutritious_food','Makanan Berkhasiat',
      'makanan berkhasiat,makanan tidak berkhasiat,jagung,ayam,tomato,ikan,telur,pergi ke pasar',
      'bermain permainan papan atau meneliti gambar pasar pada Buku Teks, mengelaskan makanan berkhasiat dan menerangkan kepentingannya tanpa membandingkan bentuk atau berat tubuh murid',
      'Mari Pergi ke Pasar',
      'Pemain melontar dadu dan bergerak pada papan. Apabila berhenti, murid memilih kad makanan, menentukan sama ada pilihan berkhasiat dan memberikan satu sebab sebelum meneruskan giliran.',
      'nama makanan, pengelasan dan sebab pilihan berkhasiat',
      'Buku Teks, papan permainan, dadu, kad makanan, bakul pasar'),
    ('food_storage','Makanan Bersih dan Selamat',
      'simpan makanan,peti sejuk,ditutup,almari makanan,makanan dan minuman bersih,penyimpanan makanan',
      'meneliti gambar peti sejuk, bekas bertutup dan almari makanan, kemudian memadankan makanan atau minuman dengan cara penyimpanan yang bersih serta selamat',
      'Rumah Makanan',
      'Kumpulan menerima kad makanan dan tiga rumah: PETI SEJUK, BEKAS BERTUTUP dan ALMARI MAKANAN. Kad diletakkan selepas murid menyatakan sebab pilihan penyimpanan.',
      'tempat penyimpanan, keadaan bersih atau bertutup dan alasan keselamatan makanan',
      'Buku Teks, kad makanan dan minuman, tiga papan tempat simpanan, kad sebab'),
    ('healthy_mealtimes','Makan Berkhasiat Mengikut Waktu',
      'sarapan,makan tengah hari,makan malam,waktu makan,menu makanan berkhasiat,sarapan berkhasiat',
      'meneliti contoh menu Buku Teks, menyusun makanan berkhasiat mengikut sarapan, makan tengah hari atau makan malam dan menghasilkan satu contoh sarapan berkhasiat secara kreatif',
      'Jam Menu Sihat',
      'Murid memutar jarum masa kepada sarapan, tengah hari atau malam, kemudian memilih kad makanan untuk membina menu yang sesuai. Kumpulan menerangkan satu sebab bagi menu sebelum semakan sumber.',
      'waktu makan, kandungan menu dan sebab pilihan berkhasiat',
      'Buku Teks, jam waktu makan, kad makanan, pinggan kertas atau templat menu'),
    ('emergency_response','Kenali Kecemasan dan Minta Bantuan',
      'situasi kecemasan,minta bantuan,kemalangan,talian kecemasan,ambulans,polis,menelefon,menjerit',
      'mengikuti cerita bergambar kemalangan pada Buku Teks, mengenal pasti situasi kecemasan, menyusun tindakan meminta bantuan guru atau orang dewasa dan membezakan penggunaan talian kecemasan yang betul',
      'Rantaian Bantuan Kecemasan',
      'Kumpulan menyusun kad LIHAT SITUASI, JAGA JARAK SELAMAT, PANGGIL ORANG DEWASA, TERANGKAN LOKASI dan TUNGGU ARAHAN. Aktiviti hanya menggunakan situasi rekaan dan tidak mensimulasikan kecederaan.',
      'pengenalpastian kecemasan, urutan meminta bantuan dan maklumat yang perlu disampaikan',
      'Buku Teks, kad situasi rekaan, kad urutan bantuan, kad watak guru-polis-ambulans')
), activity_rows(
  level_key, phase, suffix, row_name, pak21, is_game, priority,
  selection_weight, template
) as (
  values
    ('support','input','picture_cue','Lihat, Tunjuk dan Sebut','Think-Pair-Share',false,20,138,
      'Guru membuka {{page}} dan membimbing murid meneliti satu gambar, dialog atau arahan utama. Menggunakan dua kad petunjuk, murid mula %1$s. Guru menyemak istilah dan tindakan pertama sebelum tugasan penuh.'),
    ('support','guided','guided_source','Tugasan Buku Berpandu','I Do-We Do',false,21,144,
      'Murid melaksanakan tugasan asal pada {{page}} secara satu bahagian demi satu bahagian untuk %1$s. Guru memodelkan satu contoh menggunakan watak atau situasi rekaan, kemudian pasangan melengkapkan dua item seterusnya.'),
    ('support','evidence','choose_evidence','Pilih Bukti Bergambar','Show Me',false,22,136,
      'Murid memilih satu kad jawapan yang menunjukkan %3$s, menunjuk gambar atau kata kunci yang menyokong pilihan pada {{page}} dan menyebut satu ayat lengkap. Pengalaman peribadi murid tidak diminta.'),
    ('core','practice','source_practice','Perhati, Pilih dan Jelaskan','Pair Check',false,30,146,
      'Secara berpasangan, murid menggunakan gambar, dialog dan arahan pada {{page}} untuk %1$s. Murid pertama membuat pilihan, murid kedua mencari bukti pada halaman, kemudian mereka bertukar peranan.'),
    ('core','game','source_game','Permainan Berdasarkan Buku','Game-Based Learning',true,31,152,
      '%2$s Selepas setiap pusingan, kumpulan merekod atau menyebut satu bukti tentang %3$s dan membetulkan jawapan dengan merujuk semula {{page}}.'),
    ('core','sharing','explain_choice','Meja Pakar Kesihatan','World Cafe',false,32,140,
      'Setiap kumpulan menyiapkan satu bahagian tugasan pada {{page}}. Seorang wakil menerangkan %3$s, manakala pelawat menambah satu soalan, contoh rekaan atau bukti sebelum rumusan dibuat.'),
    ('challenge','practice','cause_action','Sebab, Kesan dan Tindakan','Think-Write-Pair-Share',false,40,144,
      'Selepas tugasan Buku Teks pada {{page}} selesai, murid membina rantaian sebab-kesan-tindakan berkaitan %3$s. Setiap anak panah disokong oleh gambar, dialog atau arahan sumber.'),
    ('challenge','game','decision_challenge','Cabaran Pilihan Bijak','Team Challenge',true,41,150,
      '%2$s Pada pusingan cabaran, kumpulan membandingkan dua pilihan, menentukan tindakan yang lebih sihat atau selamat dan mempertahankan pilihan menggunakan bukti daripada {{page}}.'),
    ('challenge','evidence','design_message','Pesanan Kesihatan Berbukti','Gallery Walk',false,42,140,
      'Murid menghasilkan kad pesanan, peta urutan atau dialog ringkas tentang %3$s berdasarkan {{page}}. Rakan menyemak ketepatan kepada sumber, kejelasan tindakan dan kesesuaian bahasa Tahun 1.')
)
insert into public.rph_activity_library (
  activity_key, language_code, skill_key, phase, level_key, activity_name,
  activity_template, bbm_template, pak21, objective_keywords, source_keywords,
  year_min, year_max, is_game, priority, active, subject_key, pedagogy_key,
  activity_type, example_text, requires_source, selection_weight, subskill_key
)
select
  format('health_y1_%s_%s', p.pattern_key, a.suffix),
  'ms', 'health_education', a.phase, a.level_key,
  format('%s: %s', p.pattern_name, case when a.is_game then p.game_name else a.row_name end),
  format(a.template, p.source_task, p.game_rule, p.evidence),
  p.bbm, a.pak21,
  array[p.pattern_name, p.pattern_key]::text[],
  string_to_array(p.source_words, ','),
  1, 1, a.is_game, a.priority, true, 'health', 'source_first_health',
  format('health_%s_%s', p.pattern_key, a.suffix),
  'Digunakan selepas tugasan Buku Teks sebenar bagi tajuk, minggu dan Standard Pembelajaran yang sama dikenal pasti.',
  true, a.selection_weight, p.pattern_key
from patterns p cross join activity_rows a
on conflict (activity_key) do update set
  activity_name=excluded.activity_name,
  activity_template=excluded.activity_template,
  bbm_template=excluded.bbm_template,
  pak21=excluded.pak21,
  objective_keywords=excluded.objective_keywords,
  source_keywords=excluded.source_keywords,
  activity_type=excluded.activity_type,
  example_text=excluded.example_text,
  requires_source=true,
  selection_weight=excluded.selection_weight,
  subskill_key=excluded.subskill_key,
  active=true;

with patterns(pattern_key, pattern_name, source_words, induction_focus, bbm) as (
  values
    ('body_knowledge','Kenali Anggota Tubuh','anggota tubuh,bahagian tubuh,deria','memadankan satu anggota tubuh dengan fungsi atau deria yang sesuai','Buku Teks, kad anggota tubuh, kad fungsi deria'),
    ('personal_hygiene','Kebersihan Fizikal','kebersihan fizikal,mandi,cuci tangan,potong kuku,pakaian bersih','menyusun dua gambar amalan kebersihan mengikut urutan yang betul','Buku Teks, kad rutin kebersihan, kad alatan diri'),
    ('personal_boundaries','Sentuhan Selamat','sentuhan selamat,sentuhan tidak selamat,sentuhan tidak selesa,berkata tidak','memilih tindakan TIDAK, BEREDAR atau BERITAHU bagi satu situasi rekaan tanpa berkongsi pengalaman peribadi','Buku Teks, kad situasi rekaan, kad tindakan selamat'),
    ('medicine_safety','Ubat yang Selamat','ubat,preskripsi,tarikh luput,penyimpanan ubat','memilih satu penggunaan atau tempat penyimpanan ubat yang betul menggunakan kad rekaan','Buku Teks, kad label ubat rekaan, kad tempat simpanan'),
    ('emotion_identification','Kenali Emosi','emosi,gembira,sedih,takut,marah,malu','meneka satu emosi dan menyatakan petunjuk pada ekspresi atau situasi','Buku Teks, kad emosi, kad situasi rekaan'),
    ('needs_wants','Keperluan dan Kehendak','keperluan,kehendak,membeli-belah','mengelaskan dua kad barang sebagai keperluan atau kehendak','Buku Teks, kad barang, dua bakul kategori'),
    ('emotion_management','Urus Emosi','meluahkan emosi,mengurus emosi,jaga emosi','memilih satu ayat atau tindakan yang sesuai untuk mengurus emosi watak rekaan','Buku Teks, kad emosi, kad Tangga Tenang'),
    ('family_roles','Peranan Keluarga','peranan ahli keluarga,penjaga,peranan di rumah','memadankan satu watak dengan satu peranan atau tindakan membantu','Buku Teks, kad watak, kad tugasan rumah'),
    ('family_uniqueness','Keistimewaan Keluarga','keistimewaan diri,hobi,kebolehan,minat','memadankan satu hobi atau kebolehan dengan watak pada halaman sumber','Buku Teks, kad hobi dan kebolehan, papan bingo'),
    ('family_respect','Hormat dan Bantu','hormat keluarga,bantu-membantu,adab di rumah,komunikasi keluarga','melengkapkan satu dialog rumah dengan ungkapan sopan yang sesuai','Buku Teks, kad dialog, kad situasi rumah'),
    ('healthy_relationships','Hubungan Sihat','hubungan yang sihat,etika perhubungan,rakan,jiran','memadankan satu hubungan dengan etika komunikasi yang sesuai','Buku Teks, kad watak, kad etika'),
    ('relationship_refusal','Berkata TIDAK','jangan sentuh saya,berkata tidak,tempat selamat,minta pertolongan','menyusun tindakan berkata TIDAK, beredar dan memberitahu orang dewasa yang dipercayai','Buku Teks, kad tiga tindakan, kad bantuan'),
    ('germ_spread','Cara Kuman Merebak','kuman merebak,sentuhan,udara,makanan kotor,minuman kotor','memadankan kuman dengan satu cara penyebaran dan satu tindakan pencegahan','Buku Teks, kad laluan kuman, kad tindakan'),
    ('germ_disease','Penyakit Bawaan Kuman','penyakit bawaan kuman,batuk,bersin,penyakit kulit,cirit-birit','meneka penyakit daripada satu petunjuk umum pada kad sumber','Buku Teks, kad petunjuk, kad penyakit'),
    ('disease_prevention','Cegah Penyakit','cuci tangan,tutup mulut,batuk,bersin,sapu tangan,mandi','memilih satu amalan kebersihan yang membantu mencegah penyakit','Buku Teks, kad amalan kebersihan, papan perisai'),
    ('environmental_safety','Situasi Tidak Selamat','situasi tidak selamat,orang tidak dikenali,diikuti,beritahu guru','mengenal pasti satu petunjuk bahaya dan memilih tindakan selamat','Buku Teks, kad situasi rekaan, peta laluan selamat'),
    ('bullying_prevention','Elakkan Buli','buli,pembuli,dibuli,jangan ganggu saya','memilih tindakan berkata TIDAK, beredar atau memberitahu guru bagi situasi rekaan','Buku Teks, kad situasi rekaan, kad tindakan anti-buli'),
    ('nutritious_food','Makanan Berkhasiat','makanan berkhasiat,makanan tidak berkhasiat,pergi ke pasar','memilih satu makanan berkhasiat dan memberikan sebab tanpa membandingkan tubuh murid','Buku Teks, kad makanan, bakul pasar'),
    ('food_storage','Simpan Makanan','peti sejuk,ditutup,almari makanan,penyimpanan makanan','memadankan satu makanan dengan tempat penyimpanan yang bersih dan selamat','Buku Teks, kad makanan, papan tempat simpanan'),
    ('healthy_mealtimes','Waktu Makan Sihat','sarapan,makan tengah hari,makan malam,waktu makan','menyusun tiga kad waktu makan dan memilih satu makanan yang sesuai','Buku Teks, jam waktu makan, kad makanan'),
    ('emergency_response','Minta Bantuan Kecemasan','situasi kecemasan,minta bantuan,talian kecemasan,ambulans,polis','menyusun tindakan menjaga jarak selamat, memanggil orang dewasa dan menerangkan lokasi','Buku Teks, kad situasi rekaan, kad urutan bantuan')
), induction_rows(suffix, induction_type, row_name, pak21, priority, template) as (
  values
    ('visual_clue','visual','Teka Fokus Gambar','Think-Pair-Share',20,
      'Guru memaparkan satu gambar atau tajuk kecil daripada {{page}}. Murid %1$s, kemudian menyemak jangkaan bersama pasangan sebelum membaca arahan asal.'),
    ('scenario_sort','scenario','Pilih Kad Tindakan','Scenario Sort',22,
      'Guru menunjukkan dua kad situasi rekaan berkaitan {{page}}. Murid %1$s dan mengangkat kad pilihan sebelum menyemak maklumat Buku Teks.'),
    ('source_puzzle','game','Puzzle Maklumat Buku','Pair Check',24,
      'Pasangan menyusun tiga kad kata kunci atau gambar daripada fokus {{page}}. Murid menggunakan susunan itu untuk %1$s, kemudian menyemak jawapan dengan halaman Buku Teks.')
)
insert into public.rph_induction_library (
  induction_key, subject_key, skill_key, language_code, induction_type,
  induction_name, induction_template, example_text, bbm_template, pak21,
  objective_keywords, source_keywords, year_min, year_max, priority,
  selection_weight, active, subskill_key
)
select
  format('health_y1_%s_%s', p.pattern_key, i.suffix),
  'health', 'health_education', 'ms', i.induction_type,
  format('%s: %s', p.pattern_name, i.row_name),
  format(i.template, p.induction_focus),
  'Set induksi menggunakan gambar, dialog atau arahan halaman sumber dan tidak menggantikan tugasan Buku Teks.',
  p.bbm, i.pak21,
  array[p.pattern_name, p.pattern_key]::text[],
  string_to_array(p.source_words, ','),
  1, 1, i.priority, 134, true, p.pattern_key
from patterns p cross join induction_rows i
on conflict (induction_key) do update set
  induction_name=excluded.induction_name,
  induction_template=excluded.induction_template,
  example_text=excluded.example_text,
  bbm_template=excluded.bbm_template,
  pak21=excluded.pak21,
  objective_keywords=excluded.objective_keywords,
  source_keywords=excluded.source_keywords,
  selection_weight=excluded.selection_weight,
  subskill_key=excluded.subskill_key,
  active=true;

insert into public.rph_subject_pedagogy (
  subject_key, subject_name, language_code, direction, pedagogy_notes,
  preferred_methods, preferred_bbm, active
)
values (
  'health', 'Pendidikan Kesihatan', 'ms', 'ltr',
  'RPT menentukan minggu dan SK/SP; DSKP mengesahkan standard; Buku Teks menentukan gambar, dialog, soalan dan hasil sebenar. Semua kumpulan melaksanakan tugasan sumber yang sama. Tahun 1 menggunakan arahan pendek, visual, kad pilihan dan simulasi berasaskan watak rekaan. Topik batas tubuh, buli dan keselamatan tidak meminta pendedahan pengalaman peribadi, tidak melakonkan sentuhan dan mengutamakan bantuan orang dewasa yang dipercayai. Ubat hanya menggunakan label rekaan, pemakanan tidak membandingkan tubuh murid dan kecemasan tidak mensimulasikan kecederaan.',
  array['Think-Pair-Share','Scenario Sort','Decision Cards','Pair Check','Game-Based Learning','World Cafe','Gallery Walk'],
  array['Buku Teks','kad gambar dan kata kunci','kad situasi rekaan','kad keputusan','papan kategori','kad urutan','bahan simulasi bersih'],
  true
)
on conflict (subject_key) do update set
  subject_name=excluded.subject_name,
  language_code=excluded.language_code,
  direction=excluded.direction,
  pedagogy_notes=excluded.pedagogy_notes,
  preferred_methods=excluded.preferred_methods,
  preferred_bbm=excluded.preferred_bbm,
  active=true;
