// Temporary loader for the RPH routing / verified-map / teacher-review / quality hotfixes.
// Keeps the canonical app blob unchanged while loading small patches after it.
document.write('<script src="app-v03334-original.js?v=rph-week-route-20260904"><\/script>');
document.write('<script src="rph-week-routing-hotfix.js?v=20260904b"><\/script>');
document.write('<script src="lessonmap-review-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-quality-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-bm-year1-source-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-bm-year1-unit17-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-bm-year1-unit16-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-bm-year1-unit19-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-bm-year1-unit20-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-bm-year1-unit21-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-bm-year1-units22-24-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-bm-year2-unit1-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-bm-year2-unit1-followup-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-bm-year2-units2-3-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-science-quality-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-science-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-science-magnet-actions-blueprint-hotfix.js?v=20260904b"><\/script>');
document.write('<script src="rph-science-magnet-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-science-absorption-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-science-electric-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-science-mixture-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-science-earth-soil-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-science-year2-water-air-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-science-year2-technology-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-science-year3-source-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-science-year3-future-blueprint-hotfix.js?v=20260904a"><\/script>');
document.write('<script src="rph-english-quality-hotfix.js?v=20260904a"><\/script>');