import json, os
from pathlib import Path

base = Path('/data/data/com.termux/files/home/rph-hub/rph-library/generated/bm-year3-source-review-r1/drafts')
ids = [f'BM3-2026B-W29-S{i}' for i in range(1,6)] + [f'BM3-2026B-W30-S{i}' for i in range(1,4)]
protected = ['id','title','week','session','sp_code','sp_text','rpt_book_pages','source_evidence','source_hold','active','presentation_review','revision']

def make_phases(d, kind):
    t, p = d['title'], d['rpt_book_pages']
    src = f'Buku Teks Jilid 2 m/s {p}'
    if kind == 'kata nama':
        phases = [
          ('Set induksi',5,[f'Guru paparkan tajuk “{t}” dan minta murid membuka {src}.', 'Guru beri masa melihat gambar atau ayat tanpa menyalin jawapan.', f'Guru tanya, “Apakah benda atau orang yang kamu nampak pada halaman {p}?”'],['Murid membuka halaman yang betul.','Murid melihat gambar atau membaca ayat pendek.','Murid menyebut satu kata yang dikenal pasti.'],f'Guru tanda murid yang dapat menyebut satu kata nama daripada halaman {p}.',[src,'Papan putih']),
          ('Guru tunjuk cara',10,[f'Guru gariskan satu kata nama yang benar-benar kelihatan pada {src}.', 'Guru sebut contoh ayat berdasarkan kata itu, tanpa menambah maklumat di luar halaman.', 'Guru tanya, “Kata ini menamakan apa?” dan tunjuk cara memeriksa gambar atau ayat.'],['Murid ikut guru membaca kata yang ditunjukkan.','Murid tunjuk kata atau gambar yang menjadi bukti.','Murid bezakan kata nama daripada satu kad kata lain.'], 'Semak murid menyebut kata dan menghubungkannya dengan benda, orang atau tempat pada sumber.',[src,'Kad kata nama','Papan putih']),
          ('Bina jawapan bersama',15,[f'Guru pilih dua kata yang murid nampak pada {src} dan tulis pada papan.', 'Guru tanya, “Kata yang manakah sesuai untuk melengkapkan ayat ini?”', 'Guru baca ayat contoh dan minta murid memberi sebab berdasarkan gambar atau ayat sumber.'],['Murid pilih kad kata yang sesuai.','Murid membaca ayat lengkap bersama-sama.','Murid menerangkan kata itu merujuk kepada apa.'], 'Semak pilihan kad, sebutan dan kesesuaian kata dengan bukti pada halaman.',[src,'Kad kata/gambar','Papan putih']),
          ('Latihan pasangan',15,[f'Guru beri setiap pasangan salinan kad daripada {src}.', 'Guru arahkan seorang murid memilih kata dan seorang lagi membina ayat mudah.', 'Guru soal pasangan, “Di manakah bukti kata ini pada halaman {p}?” lalu betulkan ayat jika perlu.'],['Murid pilih satu kata daripada kad.','Murid bina dan baca satu ayat mudah.','Murid bertukar peranan dan menyemak ayat pasangan.'], 'Catat pasangan yang boleh memilih kata dan menggunakan kata itu dalam ayat tanpa jawapan guru.',[src,'Kad kata/gambar','Lembaran pasangan']),
          ('Hasil individu',10,[f'Guru beri lembaran individu dengan ruang “Kata daripada halaman {p}” dan “Ayat saya”.', 'Guru minta murid memilih dua kata yang dapat dilihat atau dibaca pada {src}.', 'Guru semak satu demi satu dan tanya, “Boleh tunjuk bukti kata ini?”'],['Murid menulis atau menyalin dua kata yang sesuai.','Murid membina satu ayat mudah menggunakan salah satu kata.','Murid membaca ayat kepada guru atau rakan.'], 'Semak dua kata dan satu ayat; tandakan sendiri, dengan bantuan atau belum.',[src,'Lembaran individu','Pensel']),
          ('Penutup',5,[f'Guru paparkan semula tajuk “{t}”.','Guru minta tiga murid berkongsi satu kata dan ayat.', 'Guru rumus bahawa kata nama menamakan perkara yang dirujuk dalam sumber dan tanya, “Apakah bukti kamu?”'],['Murid sebut satu kata nama.','Murid baca satu ayat yang dibina.','Murid nyatakan sama ada perlu bantuan memilih kata atau membina ayat.'], 'Gunakan jawapan lisan terakhir sebagai semakan cepat dan rekod murid yang perlu ulang kaji.',[src,'Kad kata','Senarai semak'])]
    elif kind == 'mendengar':
        phases = [
          ('Set induksi',5,[f'Guru paparkan tajuk “{t}” dan gambar pada {src}.','Guru minta murid melihat tanpa menjawab dahulu.','Guru tanya, “Apakah perkara yang kamu jangka akan didengar berdasarkan tajuk ini?”'],['Murid melihat sumber.','Murid mendengar soalan guru.','Murid menyebut satu jangkaan ringkas.'],'Catat murid yang memberi respons berkaitan tajuk.',[src,'Papan putih']),
          ('Dengar dan model',10,[f'Guru baca maklumat atau arahan yang tersedia pada {src} dengan intonasi jelas.','Guru ulang satu ayat penting dan tunjuk bahagian sumber yang berkaitan.','Guru modelkan respons lengkap: “Saya dengar bahawa …” hanya menggunakan maklumat halaman.'],['Murid mendengar tanpa menyampuk.','Murid tunjuk gambar atau ayat yang dirujuk guru.','Murid ulang respons model secara kelas.'],'Semak murid dapat memadankan ujaran dengan bahagian sumber yang ditunjukkan.',[src,'Kad kata kunci','Papan putih']),
          ('Respons bersama',15,[f'Guru baca tiga petikan atau ayat pendek daripada {src} satu demi satu.','Guru tanya, “Apakah maklumat yang kamu dengar?” dan “Apakah bukti pada halaman?”','Guru beri dua pilihan kad apabila murid sukar menjawab dan jelaskan pembetulan.'],['Murid angkat kad respons.','Murid jawab soalan secara lisan.','Murid membetulkan respons selepas mendengar bacaan semula.'],'Semak ketepatan isi respons dan keupayaan menunggu sehingga ujaran selesai.',[src,'Kad respons','Kad kata kunci']),
          ('Latihan pasangan',15,[f'Guru beri pasangan satu bahagian sumber {src} untuk diperhatikan.','Guru bacakan ayat atau maklumat berkaitan dan beri soalan, “Apa yang kamu dengar?”','Guru bergerak memerhati dan meminta pasangan menunjukkan bukti sebelum menerima jawapan.'],['Murid dengar bacaan guru.','Murid ulang maklumat kepada pasangan.','Murid bertukar peranan sebagai pendengar dan pemberi respons.'],'Rekod pasangan yang memberi respons tepat dengan atau tanpa kad bantuan.',[src,'Kad soalan','Lembaran pasangan']),
          ('Respons individu',10,[f'Guru panggil murid seorang demi seorang berdasarkan {src}.','Guru tanya satu soalan khusus tentang maklumat yang baru dibaca atau didengar.','Guru beri bacaan semula sekali sahaja jika murid meminta bantuan dan rekod tahap bantuan.'],['Murid dengar soalan hingga selesai.','Murid beri satu respons berkaitan sumber.','Murid ulang respons selepas pembetulan sebutan atau isi.'],'Tandakan respons individu: tepat sendiri, tepat dengan ulangan, atau belum tepat.',[src,'Senarai semak','Kad bantuan']),
          ('Penutup',5,[f'Guru ulang tajuk “{t}” dan satu maklumat yang didengar daripada {src}.','Guru tanya, “Apakah cara mendengar yang membantu kamu menjawab?”','Guru beritahu maklumat yang masih perlu dilatih berdasarkan rekod.'],['Murid sebut satu maklumat.','Murid tunjuk bahagian sumber yang berkaitan.','Murid nyatakan satu cara memberi respons dengan baik.'],'Gunakan jawapan akhir dan catatan bantuan untuk merancang intervensi.',[src,'Papan putih'])]
    elif kind == 'membaca':
        phases = [
          ('Set induksi',5,[f'Guru paparkan tajuk “{t}” dan minta murid membuka {src}.','Guru beri masa meneliti gambar, simbol atau teks yang benar-benar ada pada halaman.','Guru tanya, “Apakah bahagian yang paling menarik perhatian kamu?”'],['Murid membuka halaman.','Murid melihat atau membaca bahan.','Murid menyebut satu bahagian yang diperhatikan.'],'Semak murid mengenal pasti bahagian sumber sebelum membaca.',[src,'Papan putih']),
          ('Guru tunjuk bacaan',10,[f'Guru baca tajuk dan bahagian pendek pada {src} dengan sebutan jelas.','Guru tunjuk cara menggariskan kata atau maklumat penting yang tertulis pada halaman.','Guru tanya, “Apakah maklumat yang kita dapat daripada ayat atau gambar ini?”'],['Murid ikut bacaan guru.','Murid menjejak perkataan dengan jari.','Murid tunjuk maklumat penting pada sumber.'],'Semak bacaan dan bukti yang ditunjukkan, bukan jawapan yang dihafal.',[src,'Kad kata kunci','Pen penanda']),
          ('Faham bersama',15,[f'Guru pilih satu bahagian pada {src} dan baca bersama murid.','Guru beri soalan “Siapa/apa?”, “Di mana?” atau “Apakah maklumatnya?” mengikut bahan yang tersedia.','Guru minta murid menjawab dengan menunjuk bukti dan membetulkan jawapan yang tidak sepadan.'],['Murid membaca secara bergilir.','Murid jawab satu soalan.','Murid tunjuk perkataan, gambar atau ayat sebagai bukti.'],'Semak jawapan mesti bersandar pada bahagian sumber yang ditunjukkan.',[src,'Kad soalan','Lembaran bukti']),
          ('Latihan pasangan',15,[f'Guru beri pasangan petunjuk lokasi pada {src}, contohnya “cari tajuk” atau “cari ayat pertama”.','Guru minta seorang membaca dan seorang menunjuk bukti.','Guru tanya pasangan, “Apakah maklumat yang kamu pilih dan mengapa?”'],['Murid membaca bahagian yang ditetapkan.','Murid menunjuk bukti kepada pasangan.','Murid bertukar peranan dan membandingkan jawapan.'],'Catat murid yang boleh membaca dan memilih maklumat tanpa petunjuk tambahan.',[src,'Kad lokasi','Lembaran pasangan']),
          ('Bukti individu',10,[f'Guru beri lembaran dengan dua ruang maklumat daripada {src}.','Guru minta murid menulis atau melukis maklumat yang dibaca, bukan mereka cerita baharu.','Guru semak dengan soalan, “Tunjukkan tempat kamu mendapat jawapan.”'],['Murid membaca semula sumber.','Murid mengisi dua maklumat.','Murid menunjukkan bukti kepada guru.'],'Semak dua maklumat sepadan dengan bahan dan rekod bantuan membaca.',[src,'Lembaran individu','Pensel']),
          ('Penutup',5,[f'Guru kembali kepada tajuk “{t}”.','Guru minta murid menyebut satu maklumat penting dan menunjukkan buktinya.','Guru rumus langkah lihat, baca, pilih maklumat dan semak bukti.'],['Murid sebut satu maklumat.','Murid tunjuk bukti pada halaman.','Murid nyatakan langkah yang paling membantu.'],'Gunakan respons akhir untuk memilih bahan ulang kaji.',[src,'Kad langkah','Senarai semak'])]
    elif kind == 'menulis':
        phases = [
          ('Set induksi',5,[f'Guru paparkan tajuk “{t}” dan bahan pada {src}.','Guru minta murid menyebut perkara yang boleh dijadikan isi, tanpa menambah fakta baharu.','Guru tanya, “Apakah perkataan pada halaman yang boleh membantu ayat kita?”'],['Murid melihat sumber.','Murid menyebut satu perkataan atau frasa daripada halaman.','Murid berkongsi idea dengan rakan.'],'Catat murid yang boleh mengambil isi daripada sumber.',[src,'Papan putih','Kad kata']),
          ('Guru modelkan ayat',10,[f'Guru pilih satu kata atau frasa yang jelas pada {src}.','Guru susun kad menjadi ayat mudah dan baca dari huruf besar hingga tanda noktah.','Guru tanya, “Adakah ayat ini berkaitan halaman {p}?” dan tunjuk cara menyemak.'],['Murid membaca ayat model.','Murid menyusun kad mengikut urutan.','Murid menyebut sebab ayat berkaitan sumber.'],'Semak susunan ayat, makna dan tanda noktah.',[src,'Kad frasa','Papan putih']),
          ('Bina ayat bersama',15,[f'Guru tunjuk dua pilihan kata daripada {src} dan minta kelas memilih yang sesuai.','Guru bina satu ayat di papan dengan sumbangan murid.','Guru baca ayat dan tanya, “Siapa/apa melakukan perkara itu?” untuk menyemak makna.'],['Murid mencadangkan perkataan daripada sumber.','Murid menyusun ayat secara lisan.','Murid membaca dan membaiki ayat bersama guru.'],'Semak ayat mesti mempunyai maksud dan berkaitan bahan.',[src,'Kad perkataan','Papan putih']),
          ('Latihan pasangan',15,[f'Guru beri pasangan kad perkataan yang diambil daripada {src}.','Guru arahkan murid bina satu ayat dan salin pada lembaran.','Guru tanya, “Apakah bukti ayat kamu datang daripada halaman?” dan beri pembetulan khusus.'],['Murid memilih kata atau frasa.','Murid menyusun dan menulis ayat.','Murid membaca ayat kepada pasangan dan bertukar semakan.'],'Rekod murid yang menulis ayat bermakna dengan bantuan atau sendiri.',[src,'Kad perkataan','Lembaran pasangan']),
          ('Hasil individu',10,[f'Guru beri ruang menulis satu ayat berdasarkan {src}.','Guru minta murid semak huruf besar, susunan kata dan tanda noktah menggunakan tiga tanda semak.','Guru membaca ayat murid dan meminta pembetulan satu perkara jika perlu.'],['Murid pilih isi daripada halaman.','Murid tulis satu ayat sendiri.','Murid semak tiga ciri ayat dan membaiki satu kesilapan.'],'Semak hasil individu dan tandakan ciri yang dicapai.',[src,'Lembaran individu','Kad semak']),
          ('Penutup',5,[f'Guru minta dua murid membaca ayat tentang “{t}”.','Guru tanya, “Apakah yang menjadikan ayat itu bermakna?”','Guru rumus langkah pilih isi, susun ayat dan semak tulisan.'],['Murid membaca ayat.','Murid menyebut satu ciri ayat bermakna.','Murid simpan hasil untuk semakan guru.'],'Gunakan hasil individu sebagai bukti PBD akhir.',[src,'Kad semak'])]
    else:
        phases = [
          ('Set induksi',5,[f'Guru paparkan tajuk “{t}” dan bahan pada {src}.','Guru minta murid memerhati perkataan, susunan atau gambar yang tersedia.','Guru tanya, “Apakah perkataan yang menarik perhatian kamu?”'],['Murid melihat sumber.','Murid menyebut satu perkataan atau bahagian yang menarik.','Murid berkongsi sebutan dengan rakan.'],'Semak murid bersedia menggunakan bahan sumber, bukan mencipta fakta baharu.',[src,'Papan putih']),
          ('Guru tunjuk persembahan',10,[f'Guru baca atau lafazkan bahagian pendek yang terdapat pada {src}.','Guru tunjuk jeda, sebutan dan nada melalui satu contoh.','Guru tanya, “Bahagian manakah yang perlu disebut dengan jelas?”'],['Murid mendengar contoh.','Murid ikut lafaz secara perlahan.','Murid tunjuk perkataan atau baris yang dirujuk.'],'Semak sebutan dan kesediaan murid mengikut teks atau bahan yang ada.',[src,'Kad baris','Papan putih']),
          ('Bina bersama',15,[f'Guru pilih perkataan atau frasa daripada {src} untuk dibaca bersama.','Guru beri model sebutan dan minta murid mengulang secara kumpulan kecil.','Guru soal, “Apakah maksud yang kamu faham daripada bahagian ini?” tanpa memaksa jawapan panjang.'],['Murid membaca atau melafazkan secara berkumpulan.','Murid memilih perkataan yang hendak ditekankan.','Murid memberi maksud mudah berdasarkan sumber.'],'Semak sebutan, kelancaran dan kesesuaian maksud.',[src,'Kad perkataan','Kad intonasi']),
          ('Latihan pasangan',15,[f'Guru beri pasangan bahagian pendek daripada {src}.','Guru minta seorang membaca atau melafazkan dan seorang menanda sebutan jelas.', 'Guru bimbing dengan soalan, “Adakah kamu berhenti pada tempat yang sesuai?”'],['Murid berlatih sebutan.','Murid membaca kepada pasangan.','Murid bertukar peranan dan memberi satu cadangan baik.'],'Catat murid yang boleh menyampaikan bahagian sumber dengan sokongan minimum.',[src,'Kad teks','Senarai semak pasangan']),
          ('Hasil individu',10,[f'Guru pilih satu bahagian ringkas daripada {src} untuk setiap murid.','Guru beri masa murid menanda perkataan sukar dan berlatih perlahan.','Guru dengar persembahan individu dan beri satu maklum balas khusus.'],['Murid memilih bahagian yang ditetapkan.','Murid berlatih sebutan dan jeda.','Murid melafazkan atau membaca kepada guru.'],'Tandakan jelas, perlu ulang sebutan, atau belum sempat diperhatikan.',[src,'Kad teks individu','Senarai semak']),
          ('Penutup',5,[f'Guru minta dua murid menyampaikan semula satu bahagian daripada “{t}”.','Guru tanya, “Apakah yang membantu penyampaian kamu menjadi jelas?”','Guru rumus kepentingan sebutan dan nada yang sesuai dengan bahan.'],['Murid menyampaikan satu bahagian.','Murid menyebut satu perkara yang dipelajari.','Murid nyatakan latihan yang masih diperlukan.'],'Gunakan persembahan akhir dan refleksi murid untuk intervensi.',[src,'Kad refleksi'])]
    return [{'name':n,'minutes':m,'teacher':g,'pupils':s,'check':c,'resources':r} for n,m,g,s,c,r in phases]

def detail(d):
    sc=d['sp_code']
    if sc=='5.1.1': kind='kata nama'
    elif sc=='1.1.2': kind='mendengar'
    elif sc=='2.2.1': kind='membaca'
    elif sc=='3.2.2': kind='menulis'
    else: kind='sastera'
    title=d['title']; p=d['rpt_book_pages']; src=f'Buku Teks Jilid 2 m/s {p}'
    d['duration']=60
    d['duration_note']='60 minit; ikut jadual sebenar guru.'
    d['objective']={
      'kata nama':f'Murid dapat mengenal pasti dua kata nama dan menggunakan satu kata nama dalam ayat berdasarkan {src}.',
      'mendengar':f'Murid dapat memberikan satu respons lisan berdasarkan maklumat yang didengar daripada {src}.',
      'membaca':f'Murid dapat menyatakan dua maklumat penting daripada bahan pada {src}.',
      'menulis':f'Murid dapat menulis satu ayat bermakna berdasarkan {src}.',
      'sastera':f'Murid dapat menyampaikan satu bahagian ringkas daripada {src} dengan sebutan jelas.'
    }[kind]
    d['success_criteria']={
      'kata nama':['Mengenal pasti dua kata nama pada halaman sumber.','Menggunakan satu kata nama dalam ayat mudah.','Membetulkan satu pilihan kata selepas maklum balas.'],
      'mendengar':['Memberi satu respons yang berkaitan dengan maklumat didengar.','Menunjukkan bahagian sumber yang menyokong respons.','Membetulkan respons selepas mendengar ulangan.'],
      'membaca':['Membaca atau meneliti bahan pada halaman.','Menyatakan dua maklumat yang sepadan dengan sumber.','Menunjukkan bukti bagi satu maklumat.'],
      'menulis':['Memilih isi daripada bahan sumber.','Menulis satu ayat yang mempunyai maksud.','Menyemak huruf besar dan tanda noktah.'],
      'sastera':['Membaca atau melafazkan bahagian yang ditetapkan.','Menyebut dengan jelas dan jeda yang sesuai.','Membaiki satu sebutan selepas maklum balas.']
    }[kind]
    d['prior_knowledge']='Murid pernah melihat gambar, membaca ayat pendek dan menjawab soalan mudah.'
    d['bbm']=[src,f'Kad kata/gambar berkaitan {title}','Lembaran individu dan senarai semak guru']
    d['pak21']='Think-Pair-Share: lihat sumber, bincang dengan pasangan dan tunjuk bukti halaman.'
    d['values']='Menghargai alam sekitar, bekerjasama dan berani mencuba.'
    d['kbat']='Murid memilih maklumat yang sesuai daripada sumber dan memberi satu sebab mudah.'
    d['phases']=make_phases(d,kind)
    d['differentiation']={
      'support':{'label':'Peneroka — Dengan gambar dan kata kunci','task':f'Menghasilkan respons kemahiran {sc} menggunakan bahagian sumber pada halaman {p}, kad gambar dan rangka jawapan.','materials':[src,'Kad kata/gambar','Rangka ayat atau kad langkah'], 'teacher':['Guru tunjuk satu bahagian sumber dan sebut langkah pertama.','Guru beri soalan pandu, “Apakah yang kamu nampak atau dengar pada halaman ini?”','Guru modelkan satu jawapan dan minta murid membaiki satu bahagian.'],'pupil_steps':['Buka halaman dan ikut bahagian yang ditunjukkan.','Pilih kata atau maklumat daripada kad.','Cuba jawab atau hasilkan tugasan bersama guru.','Cuba semula secara individu dan tunjuk bukti sumber.'],'product':'Satu respons atau hasil individu berkaitan halaman dengan bantuan kad.','criterion':'Isi atau bentuk bahasa sepadan dengan sumber selepas bantuan diberikan.','next_step':'Ulang satu item menggunakan gambar atau kata kunci yang sama, kemudian kurangkan satu bantuan.'},
      'core':{'label':'Pembina — Dengan bahan sumber','task':f'Menghasilkan tugasan kemahiran {sc} berdasarkan bahan sebenar pada {src} dengan bantuan minimum.','materials':[src,'Kad soalan atau kata kunci','Lembaran individu'], 'teacher':['Guru tetapkan bahagian halaman dan tunjuk contoh pertama.','Guru tanya soalan pandu yang khusus kepada tajuk, “Apakah bukti pada halaman {p}?”','Guru semak hasil dan minta murid membetulkan satu kesilapan.'],'pupil_steps':['Teliti bahagian sumber yang ditetapkan.','Pilih maklumat atau perkataan yang sesuai.','Bincang dan semak dengan pasangan.','Hasilkan jawapan individu dan tunjuk bukti.'],'product':'Hasil individu yang menjawab fokus objektif berdasarkan halaman.','criterion':'Hasil tepat, berkaitan sumber dan dapat diterangkan secara ringkas.','next_step':'Cuba tugasan yang sama tanpa kad pandu pada sesi berikutnya.'},
      'challenge':{'label':'Pencabar — Dengan penjelasan ringkas','task':f'Menghasilkan tugasan kemahiran {sc} berdasarkan {src} serta menambah satu penjelasan atau bukti daripada halaman.','materials':[src,'Kad bukti','Lembaran pengayaan'], 'teacher':['Guru minta murid memilih bukti kedua daripada halaman.','Guru tanya, “Mengapa pilihan atau jawapan kamu sesuai dengan bahan?”','Guru semak ketepatan dan minta murid memperkemas satu ayat atau sebutan.'],'pupil_steps':['Teliti sumber dan pilih maklumat utama.','Hasilkan jawapan individu mengikut fokus kemahiran.','Tambah satu sebab atau bukti daripada halaman.','Sampaikan hasil kepada pasangan dan baiki selepas maklum balas.'],'product':'Hasil individu yang lengkap dengan satu bukti atau penjelasan ringkas.','criterion':'Hasil tepat, berkaitan bahan dan penjelasan dapat difahami.','next_step':'Minta murid menggunakan bukti daripada bahagian lain halaman tanpa rangka jawapan.'}
    }
    d['pbd']={'method':'Pemerhatian, soal jawab, semakan hasil individu dan persembahan ringkas.','evidence':f'Respons atau hasil individu yang merujuk {src}; catatan bantuan dan pembetulan murid.','criterion':d['objective'],'recording':'Tanda BS (boleh sendiri), BB (boleh dengan bantuan), atau BP (belum diperhatikan) bagi setiap murid.','sample_checklist':['Murid membuka dan merujuk halaman sumber yang betul.','Murid menunjukkan kemahiran utama mengikut objektif.','Murid menggunakan maklumat atau bahasa yang sepadan dengan sumber.','Murid membaiki satu kesilapan selepas maklum balas.','Tahap bantuan direkod: BS, BB atau BP.']}
    d['reflection']='____ / ____ murid mencapai objektif; ____ murid memerlukan bimbingan; ____ belum diperhatikan. Bukti yang paling kukuh: ____. Perkara yang masih keliru: ____.'
    d['intervention']=f'Bimbing kumpulan kecil menggunakan {src}, satu kad kata atau kad langkah. Guru modelkan satu contoh, murid cuba bersama, kemudian murid menghasilkan semula satu item secara individu. Rekod bantuan yang masih diperlukan.'
    return d

for ident in ids:
    path=base/(ident+'.json')
    original=json.loads(path.read_text())
    keep={k: original[k] for k in protected}
    updated=detail(original)
    for k,v in keep.items():
        if updated[k] != v:
            raise RuntimeError(f'protected field changed: {ident} {k}')
    path.write_text(json.dumps(updated,ensure_ascii=False,indent=2)+'\n')
    reread=json.loads(path.read_text())
    assert reread['id']==ident and reread['duration']==60 and len(reread['phases'])==6
    assert sum(x['minutes'] for x in reread['phases'])==60
    assert all(len(x['teacher'])>=3 and len(x['pupils'])>=3 for x in reread['phases'])
    assert all(len(x['teacher'])>=3 and len(x['pupil_steps'])>=4 for x in reread['differentiation'].values())
    assert 'sample_checklist' in reread['pbd']
    print(f'READ_BACK {path} phases=6 minutes=60 protected=ok')
print(f'UPDATED {len(ids)} files')
