import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const root=new URL('../',import.meta.url);
const moduleSource=fs.readFileSync(new URL('functions/api/bm2-hermes-review.js',root),'utf8');
const ctx={Response,Headers,console};
ctx.globalThis=ctx;vm.createContext(ctx);
vm.runInContext(moduleSource.replace('export async function onRequestGet','async function onRequestGet')+'\nthis.handler=onRequestGet;',ctx);
assert.equal(typeof ctx.handler,'function');
const request=(auth)=>({headers:new Headers(auth?{authorization:auth}:{})});
const env={SUPABASE_URL:'https://project.supabase.co',SUPABASE_ANON_KEY:'test-publishable-key'};
assert.equal((await ctx.handler({request:request(null),env})).status,401);
assert.equal((await ctx.handler({request:request('Bearer test'),env:{}})).status,503);
let valid=true,role='admin',status='allowed',queries=[];
ctx.fetch=async(url,options)=>{
 queries.push({url,authorization:options.headers.authorization,apikey:options.headers.apikey});
 if(url.endsWith('/auth/v1/user'))return Response.json(valid?{id:'00000000-0000-4000-8000-000000000000',email:'admin@example.com'}:{error:'invalid'},{status:valid?200:401});
 return Response.json([{role,status}]);
};
const req=request('Bearer test.jwt.token');
valid=false;assert.equal((await ctx.handler({request:req,env})).status,401);
valid=true;role='teacher';assert.equal((await ctx.handler({request:req,env})).status,403);
role='admin';status='blocked';assert.equal((await ctx.handler({request:req,env})).status,403);
status='allowed';
const res=await ctx.handler({request:req,env});
assert.equal(res.status,200);
assert.match(res.headers.get('cache-control'),/no-store/);
const d=await res.json();
assert.equal(d.lessons.length,33);assert.equal(d.count_original_docx,66);
assert.ok(d.lessons.every(x=>x.r1.approved===false&&x.r2.approved===false));
assert.ok(queries.every(x=>x.authorization==='Bearer test.jwt.token'&&x.apikey==='test-publishable-key'));
assert.ok(!fs.existsSync(new URL('data/bm2-hermes-m31-m37-candidates.json',root)),'Private Word source must not be deployed as static JSON');
const sw=fs.readFileSync(new URL('sw.js',root),'utf8');
assert.ok(sw.includes("u.pathname.startsWith('/api/')"),'Service worker must bypass API response cache');
const app=fs.readFileSync(new URL('rph-bm2-hermes-review.js',root),'utf8');
assert.ok(app.includes("DATA_URL='/api/bm2-hermes-review'"));
console.log('BM2 Hermes admin API: 401/403/503/200 and no-store private asset checks passed.');
