import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../rph-english-year3-module6-source-blueprint-hotfix.js',import.meta.url),'utf8');
const loader=fs.readFileSync(new URL('../app-v03334.js',import.meta.url),'utf8');
const routes=['1.2.2@55|W21|S4','2.1.1@56|W21|S5','3.2.1@57|W22|S3','4.2.3@57|W22|S4','5.3.1@55|W22|S5','1.2.5@58|W23|S1','2.1.2@59|W23|S2','3.2.2@58|W23|S3','4.2.5@59|W23|S4','5.3.1@60|W23|S5','1.2.2@61|W24|S1','2.1.5@61|W24|S2','3.2.3@62|W24|S3','4.3.2@63|W24|S4','5.3.1@62|W24|S5'];
for(const r of routes)assert.ok(src.includes(`"${r}"`)||src.includes(`'${r}'`),`missing Module 6 route ${r}`);
assert.equal(routes.length,15);
assert.ok(src.includes('Module 6: Food, please!'));
assert.ok(src.includes('I’m Hungry'));
assert.ok(src.includes('Street Food'));
assert.ok(src.includes('Ordering in a Restaurant'));
assert.ok(src.includes('My Favourite Food'));
assert.ok(src.includes('The Cooking Competition'));
assert.ok(src.includes('Revision 6'));
assert.ok(src.includes('Get Smart Plus 3 Student’s Book'));
assert.ok(src.includes('Activity Library may vary delivery only and must not determine lesson content'));
assert.ok(src.includes('Workbook activity content is not invented'));
assert.ok(src.includes('Module 6 starts at W21 S4'));
assert.ok(src.includes('Module 7 starts at W25'));
assert.equal(src.includes('Math.random'),false);
assert.equal(src.includes("mappingStatus:'VERIFIED'"),false);
assert.equal(src.includes('|W21|S1'),false);
assert.equal(src.includes('|W21|S2'),false);
assert.equal(src.includes('|W21|S3'),false);
assert.equal(src.includes('|W22|S1'),false);
assert.equal(src.includes('|W22|S2'),false);
assert.equal(src.includes('|W25|'),false);
assert.equal(src.includes("generateFlag:'CONDITIONAL'"),false);
const direct=['1.2.2@55|W21|S4','2.1.2@59|W23|S2','3.2.2@58|W23|S3','3.2.3@62|W24|S3'];
for(const r of direct)assert.ok(src.includes(r),`missing direct alignment marker ${r}`);
const module5=loader.indexOf('rph-english-year3-module5-source-blueprint-hotfix.js');
const module6=loader.indexOf('rph-english-year3-module6-source-blueprint-hotfix.js');
const quality=loader.indexOf('rph-english-quality-hotfix.js');
assert.ok(module5>=0,'English Year 3 Module 5 loader missing');
assert.ok(module6>module5,'English Year 3 Module 6 must load after Module 5');
assert.ok(quality>module6,'English Year 3 Module 6 must load before English quality fallback');
console.log('English Year 3 Module 6 source-first blueprint static guard passed:',routes.length,'routes; alignment review:',routes.length-direct.length,'conditional:',0);
