import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../rph-english-year1-revision-source-blueprint-hotfix.js',import.meta.url),'utf8');
const loader=fs.readFileSync(new URL('../app-v03334.js',import.meta.url),'utf8');
const routes=['1.2.2@4|W36|S1','2.1.1@10|W36|S2','3.2.2@22|W36|S3','4.2.5@34|W36|S4','5.3.1@46|W36|S5','1.2.5@9|W37|S1','2.1.2@21|W37|S2','3.2.3@33|W37|S3','4.3.2@45|W37|S4','5.3.1@57|W37|S5'];
for(const r of routes)assert.ok(src.includes(`'${r}'`),`missing revision route ${r}`);
assert.ok(src.includes("DIRECT_ALIGNMENT=new Set(['3.2.3@33|W37|S3'])"));
assert.ok(src.includes('Friends — Greetings Revision'));
assert.ok(src.includes('At School — Classroom Objects Revision'));
assert.ok(src.includes('Let’s Play! — Toys Revision'));
assert.ok(src.includes('Pet Show — Animals Revision'));
assert.ok(src.includes('Lunchtime — Food Revision'));
assert.ok(src.includes('Friends — Story Check Revision'));
assert.ok(src.includes('At School — Colours Poster Revision'));
assert.ok(src.includes('Let’s Play! — Spelling Game Revision'));
assert.ok(src.includes('Pet Show — Quiz Time Revision'));
assert.ok(src.includes('Lunchtime — Lunchbox Game Revision'));
assert.ok(src.includes('Activity Library may vary delivery only and must not determine revision content'));
assert.ok(src.includes('Workbook activity content is not invented'));
assert.ok(src.includes('W36-W37 are revision-only routes'));
assert.ok(src.includes('W38 is UASA and must not generate a normal English lesson'));
assert.ok(src.includes('do not invent an LP number'));
assert.ok(src.includes('_runtime_english_year1_revision_source_blueprint'));
assert.equal(src.includes('Math.random'),false);
assert.equal(src.includes("mappingStatus:'VERIFIED'"),false);
assert.equal(src.includes('|W38|'),false);
const unit4=loader.indexOf('rph-english-year1-unit4-source-blueprint-hotfix.js');
const revision=loader.indexOf('rph-english-year1-revision-source-blueprint-hotfix.js');
const quality=loader.indexOf('rph-english-quality-hotfix.js');
assert.ok(unit4>=0,'English Year 1 Unit 4 loader missing');
assert.ok(revision>unit4,'English Year 1 revision must load after Unit 4');
assert.ok(quality>revision,'English Year 1 revision must load before English quality fallback');
console.log('English Year 1 revision source-first blueprint static guard passed:',routes.length,'routes; alignment review:',routes.length-1,'conditional:',0);
