import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../rph-english-year3-module7-source-blueprint-hotfix.js',import.meta.url),'utf8');
const loader=fs.readFileSync(new URL('../app-v03334.js',import.meta.url),'utf8');
const routes=['1.1.1@65|W25|S1','2.1.3@66|W25|S2','3.2.1@67|W25|S3','4.1.2@67|W25|S4','5.1.2@65|W25|S5','1.2.1@68|W26|S1','2.1.5@69|W26|S2','3.2.2@68|W26|S3','4.2.3@69|W26|S4','5.2.1@70|W26|S5','1.2.2@71|W27|S1','2.1.2@71|W27|S2','3.2.3@72|W27|S3','4.2.4@73|W27|S4','5.3.1@72|W27|S5','1.2.4@74|W28|S1','2.1.4@74|W28|S2'];
for(const r of routes)assert.ok(src.includes(`"${r}"`)||src.includes(`'${r}'`),`missing Module 7 route ${r}`);
assert.equal(routes.length,17);
assert.ok(src.includes('Module 7: Out and about'));
assert.ok(src.includes('On the Street'));
assert.ok(src.includes('Uncle Sam’s Farm'));
assert.ok(src.includes('Rules, Rules, Rules!'));
assert.ok(src.includes('Make Street Signs'));
assert.ok(src.includes('The Secret Tunnel'));
assert.ok(src.includes('Revision 7'));
assert.ok(src.includes('Get Smart Plus 3 Student’s Book'));
assert.ok(src.includes('Activity Library may vary delivery only and must not determine lesson content'));
assert.ok(src.includes('Workbook activity content is not invented'));
assert.ok(src.includes('Module 8 starts at W28 S3'));
assert.ok(src.includes('W28 S1–S2 are CONDITIONAL'));
assert.equal(src.includes('Math.random'),false);
assert.equal(src.includes("mappingStatus:'VERIFIED'"),false);
assert.equal(src.includes('|W28|S3'),false);
assert.equal(src.includes('|W28|S4'),false);
assert.equal(src.includes('|W28|S5'),false);
assert.equal(src.includes('|W29|'),false);
const conditional=['1.2.4@74|W28|S1','2.1.4@74|W28|S2'];
for(const r of conditional)assert.ok(src.includes(r),`missing conditional route ${r}`);
const direct=['3.2.1@67|W25|S3','5.1.2@65|W25|S5','1.2.1@68|W26|S1','3.2.2@68|W26|S3','3.2.3@72|W27|S3'];
for(const r of direct)assert.ok(src.includes(r),`missing direct alignment marker ${r}`);
const module6=loader.indexOf('rph-english-year3-module6-source-blueprint-hotfix.js');
const module7=loader.indexOf('rph-english-year3-module7-source-blueprint-hotfix.js');
const quality=loader.indexOf('rph-english-quality-hotfix.js');
assert.ok(module6>=0,'English Year 3 Module 6 loader missing');
assert.ok(module7>module6,'English Year 3 Module 7 must load after Module 6');
assert.ok(quality>module7,'English Year 3 Module 7 must load before English quality fallback');
console.log('English Year 3 Module 7 source-first blueprint static guard passed:',routes.length,'routes; alignment review:',routes.length-direct.length,'conditional:',conditional.length);