import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../rph-english-year3-module8-source-blueprint-hotfix.js',import.meta.url),'utf8');
const loader=fs.readFileSync(new URL('../app-v03334.js',import.meta.url),'utf8');
const routes=['1.2.2@75|W28|S3','2.1.1@76|W28|S4','3.2.1@77|W28|S5','4.2.2@77|W29|S1','5.2.1@75|W29|S2','1.2.5@78|W29|S3','2.2.1@79|W29|S4','3.2.2@78|W29|S5','4.2.4@79|W30|S1','5.3.1@80|W30|S2','1.2.2@81|W30|S3','2.2.2@81|W30|S4','3.2.3@82|W30|S5','4.3.1@83|W31|S1','5.2.1@82|W31|S2','1.2.5@84|W31|S3','2.3.1@84|W31|S4','3.2.1@84|W31|S5'];
for(const r of routes)assert.ok(src.includes(`"${r}"`)||src.includes(`'${r}'`),`missing Module 8 route ${r}`);
assert.equal(routes.length,18);
assert.ok(src.includes('Module 8: Where were you yesterday?'));
assert.ok(src.includes('Cinema Opinions'));
assert.ok(src.includes('A City from the Past'));
assert.ok(src.includes('Kelly’s Diary'));
assert.ok(src.includes('Weekend Experiences'));
assert.ok(src.includes('Revision 8'));
assert.ok(src.includes('Get Smart Plus 3 Student’s Book'));
assert.ok(src.includes('Activity Library may vary delivery only and must not determine lesson content'));
assert.ok(src.includes('Workbook activity content is not invented'));
assert.ok(src.includes('Module 8 starts at W28 S3'));
assert.ok(src.includes('Module 9 starts at W32'));
assert.equal(src.includes('Math.random'),false);
assert.equal(src.includes("mappingStatus:'VERIFIED'"),false);
assert.equal(src.includes('|W28|S1'),false);
assert.equal(src.includes('|W28|S2'),false);
assert.equal(src.includes('|W32|'),false);
const conditional=['1.2.2@75|W28|S3','2.1.1@76|W28|S4','3.2.1@77|W28|S5'];
for(const r of conditional)assert.ok(src.includes(r),`missing conditional route ${r}`);
assert.ok(src.includes("generateFlag=conditional?'CONDITIONAL':'YES'"));
const direct=['1.2.2@75|W28|S3','2.1.1@76|W28|S4','3.2.2@78|W29|S5','3.2.3@82|W30|S5','5.2.1@82|W31|S2','1.2.5@84|W31|S3'];
for(const r of direct)assert.ok(src.includes(r),`missing direct alignment marker ${r}`);
const module7=loader.indexOf('rph-english-year3-module7-source-blueprint-hotfix.js');
const module8=loader.indexOf('rph-english-year3-module8-source-blueprint-hotfix.js');
const quality=loader.indexOf('rph-english-quality-hotfix.js');
assert.ok(module7>=0,'English Year 3 Module 7 loader missing');
assert.ok(module8>module7,'English Year 3 Module 8 must load after Module 7');
assert.ok(quality>module8,'English Year 3 Module 8 must load before English quality fallback');
console.log('English Year 3 Module 8 source-first blueprint static guard passed:',routes.length,'routes; alignment review:',routes.length-direct.length,'conditional:',conditional.length);