import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../rph-english-year3-module1-source-blueprint-hotfix.js',import.meta.url),'utf8');
const loader=fs.readFileSync(new URL('../app-v03334.js',import.meta.url),'utf8');
const routes=["1.2.1@5|W2|S1","2.1.2@6|W2|S2","3.2.1@7|W2|S3","4.1.2@7|W2|S4","5.1.1@5|W2|S5","1.2.2@8|W3|S1","2.1.5@9|W3|S2","3.2.2@8|W3|S3","4.2.4@9|W3|S4","5.3.1@10|W3|S5","1.2.5@11|W4|S1","2.2.2@11|W4|S2","3.2.3@12|W4|S3","4.3.1@13|W4|S4","5.1.1@12|W4|S5","1.3.1@14|W5|S1","2.3.1@14|W5|S2","3.2.1@14|W5|S3","4.3.2@14|W5|S4","5.3.1@14|W5|S5"];
for(const r of routes)assert.ok(src.includes(`"${r}"`)||src.includes(`'${r}'`),`missing Module 1 route ${r}`);
assert.ok(src.includes('Module 1: Welcome!'));
assert.ok(src.includes('Get Smart Plus 3 Student’s Book'));
assert.ok(src.includes('RPT_English_Year3_2025-2026_KumpulanB_Mapping.xlsx'));
assert.ok(src.includes('DSKP KSSR ENGLISH YEAR 3 SK (SEMAKAN 2017).pdf'));
assert.ok(src.includes('Activity Library may vary delivery only and must not determine lesson content'));
assert.ok(src.includes('Workbook activity content is not invented'));
assert.ok(src.includes("week1Policy:'W1 is Orientation Week"));
assert.equal(src.includes('Math.random'),false);
assert.equal(src.includes("mappingStatus:'VERIFIED'"),false);
assert.equal(src.includes('|W1|'),false);
assert.equal(src.includes("generateFlag:'CONDITIONAL'"),false);
assert.equal(routes.length,20);
const direct=["1.2.1@5|W2|S1","5.1.1@5|W2|S5","1.2.2@8|W3|S1","3.2.2@8|W3|S3","3.2.3@12|W4|S3"];
for(const r of direct)assert.ok(src.includes(r),`missing direct alignment marker ${r}`);
const revision=loader.indexOf('rph-english-year1-revision-source-blueprint-hotfix.js');
const module1=loader.indexOf('rph-english-year3-module1-source-blueprint-hotfix.js');
const quality=loader.indexOf('rph-english-quality-hotfix.js');
assert.ok(revision>=0,'English Year 1 revision loader missing');
assert.ok(module1>revision,'English Year 3 Module 1 must load after English Year 1 revision');
assert.ok(quality>module1,'English Year 3 Module 1 must load before English quality fallback');
console.log('English Year 3 Module 1 source-first blueprint static guard passed:',routes.length,'routes; alignment review:',routes.length-direct.length,'conditional:',0);
