import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../rph-english-year3-module2-source-blueprint-hotfix.js',import.meta.url),'utf8');
const loader=fs.readFileSync(new URL('../app-v03334.js',import.meta.url),'utf8');
const routes=["1.2.1@15|W6|S1","2.1.2@16|W6|S2","3.2.1@17|W6|S3","4.1.2@17|W6|S4","5.1.1@15|W6|S5","1.2.2@18|W8|S1","2.1.5@19|W8|S2","3.2.2@18|W8|S3","4.2.4@19|W8|S4","5.1.2@20|W8|S5","1.2.3@21|W9|S1","2.2.2@21|W9|S2","3.2.3@22|W9|S3","4.3.1@23|W9|S4","5.2.1@22|W9|S5","1.2.5@24|W10|S1","2.3.1@24|W10|S2"];
for(const r of routes)assert.ok(src.includes(`"${r}"`)||src.includes(`'${r}'`),`missing Module 2 route ${r}`);
assert.equal(routes.length,17);
assert.ok(src.includes('Module 2: Every day'));
assert.ok(src.includes('Mike’s Day'));
assert.ok(src.includes('People at Work'));
assert.ok(src.includes('Jim’s Day'));
assert.ok(src.includes('Career Day'));
assert.ok(src.includes('Revision 2'));
assert.ok(src.includes('Get Smart Plus 3 Student’s Book'));
assert.ok(src.includes('RPT_English_Year3_2025-2026_KumpulanB_Mapping.xlsx'));
assert.ok(src.includes('DSKP KSSR ENGLISH YEAR 3 SK (SEMAKAN 2017).pdf'));
assert.ok(src.includes('Activity Library may vary delivery only and must not determine lesson content'));
assert.ok(src.includes('Workbook activity content is not invented'));
assert.ok(src.includes("week7Policy:'W7 is Cuti Perayaan Aidilfitri"));
assert.ok(src.includes("transitionPolicy:'W10 S1–S2 belong to Module 2; W10 S3–S5 begin Module 3"));
assert.equal(src.includes('Math.random'),false);
assert.equal(src.includes("mappingStatus:'VERIFIED'"),false);
assert.equal(src.includes('|W7|'),false);
assert.equal(src.includes('@25|W10|S3'),false);
assert.equal(src.includes('@26|W10|S4'),false);
assert.equal(src.includes('@27|W10|S5'),false);
assert.equal(src.includes("generateFlag:'CONDITIONAL'"),false);
const direct=["1.2.1@15|W6|S1","5.1.1@15|W6|S5","1.2.2@18|W8|S1","2.1.5@19|W8|S2","3.2.2@18|W8|S3","3.2.3@22|W9|S3"];
for(const r of direct)assert.ok(src.includes(r),`missing direct alignment marker ${r}`);
const module1=loader.indexOf('rph-english-year3-module1-source-blueprint-hotfix.js');
const module2=loader.indexOf('rph-english-year3-module2-source-blueprint-hotfix.js');
const quality=loader.indexOf('rph-english-quality-hotfix.js');
assert.ok(module1>=0,'English Year 3 Module 1 loader missing');
assert.ok(module2>module1,'English Year 3 Module 2 must load after Module 1');
assert.ok(quality>module2,'English Year 3 Module 2 must load before English quality fallback');
console.log('English Year 3 Module 2 source-first blueprint static guard passed:',routes.length,'routes; alignment review:',routes.length-direct.length,'conditional:',0);
