import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../rph-english-year3-module10-source-blueprint-hotfix.js',import.meta.url),'utf8');
const loader=fs.readFileSync(new URL('../app-v03334.js',import.meta.url),'utf8');
const routes=['1.1.1@95|W35|S1','2.1.5@96|W35|S2','3.2.2@97|W35|S3','4.2.4@97|W35|S4','5.2.1@95|W35|S5','1.2.2@98|W36|S1','2.1.5@99|W36|S2','3.2.3@98|W36|S3','4.3.1@99|W36|S4','5.3.1@100|W36|S5','1.2.4@101|W37|S1','2.1.5@101|W37|S2','3.3.1@102|W37|S3','4.3.2@103|W37|S4','5.2.1@102|W37|S5'];
for(const r of routes)assert.ok(src.includes(`\"${r}\"`)||src.includes(`'${r}'`),`missing Module 10 route ${r}`);
assert.equal(routes.length,15);
assert.ok(src.includes('Module 10: The world around us'));
assert.ok(src.includes('Animal Comparatives Song'));
assert.ok(src.includes('Sea-animal Comparisons'));
assert.ok(src.includes('The Solar System'));
assert.ok(src.includes('Make a Solar System Mobile'));
assert.ok(src.includes('Go, Papigo, Go!'));
assert.ok(src.includes('Activity Library may vary delivery only and must not determine lesson content'));
assert.ok(src.includes('Workbook activity content is not invented; Workbook is an optional page anchor only'));
assert.ok(src.includes('W38–W39 are UASA'));
assert.ok(src.includes('p.104'));
assert.ok(src.includes('do not create or infer a p.104 RPH route'));
assert.equal(src.includes('|W38|'),false);
assert.equal(src.includes('|W39|'),false);
assert.equal(src.includes('|W40|'),false);
assert.equal(src.includes('@104|'),false);
assert.equal(src.includes('Math.random'),false);
assert.equal(src.includes("mappingStatus:'VERIFIED'"),false);
assert.equal(src.includes("generateFlag:'CONDITIONAL'"),false);
const direct=['2.1.5@96|W35|S2','3.2.2@97|W35|S3','1.2.2@98|W36|S1','2.1.5@99|W36|S2','1.2.4@101|W37|S1','2.1.5@101|W37|S2','3.3.1@102|W37|S3','5.2.1@102|W37|S5'];
for(const r of direct)assert.ok(src.includes(r),`missing direct alignment marker ${r}`);
const m9=loader.indexOf('rph-english-year3-module9-source-blueprint-hotfix.js');
const m10=loader.indexOf('rph-english-year3-module10-source-blueprint-hotfix.js');
const quality=loader.indexOf('rph-english-quality-hotfix.js');
assert.ok(m9>=0,'English Year 3 Module 9 loader missing');
assert.ok(m10>m9,'English Year 3 Module 10 must load after Module 9');
assert.ok(quality>m10,'English Year 3 Module 10 must load before English quality fallback');
console.log('English Year 3 Module 10 source-first blueprint static guard passed:',routes.length,'routes; alignment review:',routes.length-direct.length,'conditional:',0);