import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import {webcrypto} from 'node:crypto';
const req=createRequire(new URL('../rph-library/generated/bm1-library-safe-pilot-r1/.tooling/package.json',import.meta.url)),JSZip=req('jszip');
const {parseHTML}=req('linkedom');
const work=new URL('../rph-library/generated/bm1-library-safe-pilot-r1/',import.meta.url);
const c={crypto:webcrypto,TextEncoder,Blob,URL,Date,console,setTimeout,clearTimeout,JSON,Map,Set,WeakSet};c.window=c;
for(const f of ['rph-record-versions.js','rph-approved-library.js'])vm.runInNewContext(fs.readFileSync(new URL('../'+f,import.meta.url),'utf8'),c,{filename:f});
const a=c.RphRecordVersions,b=c.RphApprovedLibrary,raw=JSON.parse(fs.readFileSync(new URL('app/approved-bm1-library.json',work),'utf8')),data=await b.verifyDataset(raw);
const options={localPilot:true,subjectKey:'bm',classId:'22222222-2222-4222-8222-222222222222',className:'Kelas ujian',teacherName:'Guru ujian',date:'2026-10-05',duration:60,lessonTime:'08:00–09:00',confirmConditional:true,confirmSingingModel:true};
function map(e){const m=b.mapTemplate(data,e);return {...m,id:webcrypto.randomUUID(),subject_id:'33333333-3333-4333-8333-333333333333',verification_status:'verified',source_evidence:{...m.source_evidence,textbook:true,meta:{...m.source_evidence.meta,verification_scope:'LOCAL_PILOT_DERIVED_SOURCE'}}};}
const checks=[];async function check(n,fn){await fn();checks.push(n);}
let pilotProof=[],allProof=[];
async function verifyEntry(e){const m=map(e),ctx=b.chosenContext(data,m,options),blocks=b.contextBlocks(ctx,{text:''});assert.equal(ctx.map.objective,e.lesson.objective);assert.equal(ctx.pedagogy.sourceSteps.reduce((n,p)=>n+p.minutes,0),60);for(const k of ['support','core','challenge'])assert.ok(ctx.pedagogy.librarySteps[k][0].text.includes(e.lesson.differentiation[k].product));
 const snap=a.snapshotFromContext(ctx,{teacherId:'11111111-1111-4111-8111-111111111111',classInfo:{name:'Kelas ujian',academic_year:2026},subjectInfo:{name:'Bahasa Melayu'},reflection:{text:'',present:null,achieved:null},exportLines:blocks.map(b=>b.text),exportBlocks:blocks});
 assert.ok(blocks.some(x=>x.text.includes('A. MAKLUMAT PENGAJARAN')));assert.ok(blocks.some(x=>x.text.includes('D. AKTIVITI SUMBER DARIPADA BUKU')));assert.ok(blocks.some(x=>x.text.includes('E. PDP TERBEZA')));assert.ok(blocks.some(x=>x.text.includes('F. PENTAKSIRAN BILIK DARJAH (PBD)')));assert.ok(blocks.some(x=>x.text.includes(e.lesson.objective)));assert.ok(blocks.some(x=>x.text.includes(e.lesson.pbd.evidence)));
 const blob=await a.docxFromSnapshot(snap,JSZip),zip=await JSZip.loadAsync(await blob.arrayBuffer()),xml=await zip.file('word/document.xml').async('string');
 const {document}=parseHTML(xml);const leaf=[...document.querySelectorAll('w\\:t')].map(e=>e.textContent);assert.deepEqual(leaf,JSON.parse(JSON.stringify(blocks.map(b=>b.text))));
 const html=b.renderContext(ctx);const rendered=parseHTML(html).document.textContent||parseHTML(html).document.documentElement?.textContent||'';assert.ok(html.includes('A. MAKLUMAT PENGAJARAN'));assert.ok(html.includes('D. AKTIVITI SUMBER DARIPADA BUKU'));assert.ok(html.includes('E. PDP TERBEZA'));assert.ok(html.includes('F. PENTAKSIRAN BILIK DARJAH (PBD)'));assert.ok(html.includes(e.lesson.objective));assert.ok(html.includes(e.lesson.pbd.evidence));
 return {id:e.id,minutes:60,blocks:blocks.length,docx_bytes:blob.size,all_approved_blocks_retained:true};}
await check('Pilot M29 S1-S5 first: exact content through materializer, preview and Word',async()=>{for(const e of data.entries.filter(e=>e.week===29))pilotProof.push(await verifyEntry(e));assert.equal(pilotProof.length,5);fs.writeFileSync(new URL('pilot-five-test-report.json',work),JSON.stringify({status:'PASS',rows:pilotProof},null,2)+'\n');});
await check('Then every approved route retains its reviewed blocks and Word text',async()=>{for(const e of data.entries)allProof.push(await verifyEntry(e));assert.equal(allProof.length,38);});
const first=data.entries[0],m=map(first);const rejected=(fn,code)=>assert.throws(fn,e=>e.code===code);
await check('Wrong SP/page/subfocus/duration and unverified maps blocked',()=>{rejected(()=>b.select(data,{...m,sp:'1.2.1'},options),'SP_SCOPE_MISMATCH');rejected(()=>b.select(data,{...m,textbook_page_start:110},options),'PAGE_MISMATCH');rejected(()=>b.select(data,{...m,verification_status:'draft'},options),'LESSON_MAP_NOT_VERIFIED');rejected(()=>b.select(data,{...m,source_evidence:{...m.source_evidence,meta:{...m.source_evidence.meta,sp_focus:'(i)'}}},options),'SP_SUBFOCUS_MISMATCH');rejected(()=>b.select(data,m,{...options,duration:30}),'DURATION_MISMATCH');});
await check('Map must bind exact ID, reviewed content hash and approval manifest',()=>{for(const key of ['reviewed_lesson_id','reviewed_content_sha256','approval_manifest_sha256'])rejected(()=>b.select(data,{...m,source_evidence:{...m.source_evidence,meta:{...m.source_evidence.meta,[key]:'stale'}}},options),'MAP_APPROVAL_BINDING_MISSING');});
await check('Conditional calendar and singing preflight not auto-accepted',()=>{const e=data.entries.find(e=>e.source_conditional);rejected(()=>b.select(data,map(e),{...options,confirmConditional:false}),'CONDITIONAL_CALENDAR_CONFIRMATION');const s=data.entries.find(e=>e.requires_teacher_singing_model);rejected(()=>b.select(data,map(s),{...options,confirmSingingModel:false}),'TEACHER_SINGING_MODEL_REQUIRED');});
await check('Held M34S3 and all special slots blocked, not silently replaced',()=>{for(const e of data.blocked_routes)rejected(()=>b.select(data,{...m,week_no:e.week,session_no:e.session},options),e.status);});
await check('Local map cannot impersonate a live verified map',()=>{rejected(()=>b.select(data,m,{...options,localPilot:false}),'LOCAL_MAP_NOT_REMOTE_VERIFIED');});
await check('Flexible date retains selected week/session',()=>{const x=b.select(data,m,{...options,date:'2026-11-03'});assert.equal(x.entry.id,first.id);rejected(()=>b.select(data,m,{...options,date:'2026-02-31'}),'INVALID_DATE');});
await check('Two restaurant sessions keep different products and content',()=>{const e4=data.entries.find(e=>e.id==='BM1-2026B-W36-S4'),e5=data.entries.find(e=>e.id==='BM1-2026B-W36-S5');assert.notEqual(e4.content_sha256,e5.content_sha256);assert.notEqual(e4.lesson.pbd.evidence,e5.lesson.pbd.evidence);});
await check('Tampered or duplicate dataset is rejected',async()=>{const t=a.clone(raw);t.entries[0].lesson.objective='changed';await assert.rejects(b.verifyDataset(t),e=>e.code==='ENTRY_PAYLOAD');const d=a.clone(raw);d.entries[1]=d.entries[0];await assert.rejects(b.verifyDataset(d),e=>e.code==='DATASET_COUNT');});
await check('Out-of-scope subjects remain untouched',()=>{assert.equal(b.select(data,{...m,year:2},options).status,'OUT_OF_SCOPE');assert.equal(b.select(data,m,{...options,subjectKey:'science'}).status,'OUT_OF_SCOPE');});
await check('Local arming is explicit, limits enabled routes and disarms',()=>{assert.equal(b.currentSelection(m,options),null);b.armLocal(data,{enabledIds:[first.id]});assert.equal(b.currentSelection(m,options).approvedLibrary.id,first.id);rejected(()=>b.currentSelection(map(data.entries[1]),options),'PILOT_ROUTE_NOT_ENABLED');b.disarm();assert.equal(b.currentSelection(m,options),null);});
const report={status:'PASS',checks:checks.length,names:checks,pilot_first:pilotProof,all_approved_sessions:allProof,held_count:data.blocked_routes.filter(x=>x.status==='HELD_SUBFOCUS').length,scope:'Actual approved source JSON, runtime module, HTML and real DOCX ZIP/XML parity in Node; no remote activation or visual browser claim.'};fs.writeFileSync(new URL('approved-library-test-report.json',work),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,checks:report.checks,pilot:pilotProof.length,all_sessions:allProof.length,blocked_routes:data.blocked_routes.length}));