import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import {webcrypto} from 'node:crypto';
const work=new URL('../rph-library/generated/bm1-library-safe-pilot-r1/',import.meta.url);
if(!fs.existsSync(new URL('app/approved-bm1-library.json',work))||!fs.existsSync(new URL('.tooling/node_modules',work))){console.log(JSON.stringify({status:'SKIP',reason:'gitignored rph-library fixtures absent',test:'rph-canonical-approved-flow'}));process.exit(0);}
const req=createRequire(new URL('.tooling/package.json',work));
const acorn=req('acorn'),JSZip=req('jszip'),{parseHTML}=req('linkedom');
const source=fs.readFileSync(new URL('../app-v03334-original.js',import.meta.url),'utf8');
// Real canonical function declarations; startup/auth/network side effects are not executed in this VM.
const functions=acorn.parse(source,{ecmaVersion:'latest'}).body.filter(n=>n.type==='FunctionDeclaration').map(n=>source.slice(n.start,n.end)).join('\n');
const inputIds=['rphClass','rphSubject','rphWeek','rphDate','rphTime','rphLessonMap','rphReflectionText','rphRefNote','rphRefPresent','rphRefAchieved','rphRefActive','rphRefTotal'];
const {document,window:dom}=parseHTML('<html><body>'+inputIds.map(i=>'<input id="'+i+'">').join('')+'<div id="rphEmpty"></div><div id="rphPreview" class="hidden"></div><div id="rphAccuracyGate"></div></body></html>');
const owner='11111111-1111-4111-8111-111111111111',classId='22222222-2222-4222-8222-222222222222',subjectId='33333333-3333-4333-8333-333333333333';
const state={connected:true,user:{id:owner,email:'test@example.invalid'},access:{status:'allowed'},profile:{full_name:'Guru ujian'},classes:[{id:classId,name:'Kelas ujian',year:1,academic_year:2026}],subjects:[{id:subjectId,name:'Bahasa Melayu',code:'BM'}],students:[],rphRecords:[],rphLegacyRecords:[],rphRecordVersions:[],rphActivityLibrary:[]};
const c={state,document,console,crypto:webcrypto,TextEncoder,TextDecoder,Blob,URL,Date,JSON,Map,Set,WeakSet,JSZip,DOMException:dom.DOMException,setTimeout,clearTimeout,DOCX_MIME:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',$:s=>document.querySelector(s),$$:s=>[...document.querySelectorAll(s)],setInterval:()=>0,clearInterval(){}};c.window=c;c.globalThis=c;
vm.createContext(c);vm.runInContext(functions,c);
for(const f of ['rph-record-versions.js','rph-approved-library.js'])vm.runInContext(fs.readFileSync(new URL('../'+f,import.meta.url),'utf8'),c,{filename:f});
const a=c.RphRecordVersions,b=c.RphApprovedLibrary,data=await b.verifyDataset(JSON.parse(fs.readFileSync(new URL('app/approved-bm1-library.json',work),'utf8')));
const messages=[];let oldBlueprintCalls=0,map,currentEntry;
Object.assign(c,{requireAuth:()=>true,isAdmin:()=>true,selectedRphSchedule:()=>null,timetableLessonRoute:()=>({available:false}),rphSubjectKey:()=> 'bm',lessonLanguage:()=> 'ms',selectVerifiedLessonMap:()=>map,lessonMapWeekDisposition:()=>({blocked:false}),lessonPageEvidence:async()=>({bt:[{printed_page:currentEntry.printed_pages[0],content:currentEntry.lesson.source_task,doc:{file_name:'Real locally checked source text'}}],ba:[],hasBA:false}),buildSourceActivities:()=>({activities:[currentEntry.lesson.source_task],exactTextbookCount:1,similarity:0}),effectiveRphLessonMap:()=>{oldBlueprintCalls++;throw Error('Old blueprint must be bypassed')},buildSourceAwarePedagogy:()=>{oldBlueprintCalls++;throw Error('Old pedagogy must be bypassed')},ensureRphClassroomBrowser(){},updateClassroomAssignmentActions(){},logAudit:async()=>{},toast:(s)=>messages.push(s),snippet:(s,n)=>s.slice(0,n),safeFileName:s=>s.replace(/[^A-Za-z0-9._-]/g,'_')});
for(const [id,value]of Object.entries({rphClass:classId,rphSubject:subjectId,rphWeek:'29',rphDate:'2026-10-05',rphTime:'08:00–09:00'}))document.getElementById(id).value=value;
b.armLocal(data,{enabledIds:data.entries.map(e=>e.id)});c.rphApprovedPreflight={conditional:true,singingModel:true};
const checks=[],rows=[];async function test(name,fn){await fn();checks.push(name)}
function setup(e){currentEntry=e;const t=b.mapTemplate(data,e);map={...t,id:webcrypto.randomUUID(),subject_id:subjectId,confidence_score:100,verification_status:'verified',source_evidence:{...t.source_evidence,textbook:true,meta:{...t.source_evidence.meta,verification_scope:'VM_TEST_FIXTURE_OF_VERIFIED_MAP_NOT_LIVE'}}};document.getElementById('rphWeek').value=String(e.week);}
await test('Actual canonical generateRphContent + buildDocxBlob preserve all 38 accepted lesson bodies',async()=>{
 for(const e of data.entries){setup(e);await c.generateRphContent();const ctx=state.currentGeneratedRph;assert.equal(ctx?.approvedLibrary?.id,e.id);assert.equal(ctx.map.objective,e.lesson.objective);assert.equal(document.getElementById('rphRefPresent').value,'');const html=document.getElementById('rphPreview').innerHTML;assert.ok(document.getElementById('rphPreview').hasAttribute('data-approved-rph'));const blob=await c.buildDocxBlob(ctx),zip=await JSZip.loadAsync(await blob.arrayBuffer()),xml=await zip.file('word/document.xml').async('string');const doc=parseHTML(xml).document;const texts=[...doc.querySelectorAll('w\\:t')].map(x=>x.textContent);const L=e.lesson,combined=texts.join('\n');assert.ok(combined.includes(L.title||L.source_title),`Word missing approved title`);assert.ok(combined.includes(e.id),`Word missing approved ID`);assert.ok(combined.includes(L.objective),`Word missing objective`);for(const cr of [].concat(L.success_criteria||[]))assert.ok(combined.includes(cr),`Word missing criterion`);assert.ok(combined.includes(L.sp_code),`Word missing SP code`);for(const lane of ['support','core','challenge'])for(const st of (L.differentiation[lane].pupil_steps||[]))assert.ok(combined.includes(st),`Word missing ${lane} step`);for(const g of ['Kelompok Peneroka','Kelompok Pembina','Kelompok Pencabar'])assert.ok(combined.includes(g),`Word missing ${g}`);for(const sec of ['A. MAKLUMAT PENGAJARAN','B. PENJAJARAN KURIKULUM','C. SET INDUKSI','D. AKTIVITI SUMBER DARIPADA BUKU','E. PDP TERBEZA','F. PENTAKSIRAN BILIK DARJAH (PBD)','G. PENUTUP DAN REFLEKSI'])assert.ok(combined.includes(sec),`Word missing section ${sec}`);rows.push({id:e.id,docx_bytes:blob.size,hub_section_format:true});}
 assert.equal(oldBlueprintCalls,0);
});
await test('Actual canonical save appends RPC and requires full record readback, never legacy upsert',async()=>{
 let lastPayload,written;
 state.client={rpc:async(name,args)=>{assert.equal(name,'save_rph_record_version');lastPayload=args.p_payload;written={...lastPayload,id:webcrypto.randomUUID(),revision_no:1,created_at:new Date().toISOString()};return {data:written};},from(name){assert.equal(name,'rph_record_versions');return {select(){return this},eq(){return this},single:async()=>({data:written})}}};
 assert.equal(await c.saveGeneratedRphRecord(state.currentGeneratedRph),true);assert.equal(lastPayload.snapshot.lesson.id,currentEntry.id);assert.equal(lastPayload.session_no,4);assert.ok(lastPayload.snapshot.export_lines.some(x=>x.includes(currentEntry.lesson.objective)));assert.equal(lastPayload.snapshot.reflection.present,null);assert.equal(state.rphRecordVersions.length,1);assert.ok(messages.at(-1).includes('dibaca balik'));
 state.client.rpc=async()=>({error:{message:'database unavailable'}});assert.equal(await c.saveGeneratedRphRecord(state.currentGeneratedRph),false);assert.equal(state.rphRecordVersions.length,1);
});
await test('Global exact-session/parity wrappers cannot replace approved preview/export blocks',async()=>{setup(data.entries[0]);await c.generateRphContent();for(const f of ['rph-export-parity-hotfix.js','rph-exact-session-gold-standard-hotfix.js','rph-exact-session-differentiation-export-hotfix.js','rph-differentiated-pbd-preview-hotfix.js'])vm.runInContext(fs.readFileSync(new URL('../'+f,import.meta.url),'utf8'),c,{filename:f});const blob=await c.buildDocxBlob(state.currentGeneratedRph),z=await JSZip.loadAsync(await blob.arrayBuffer()),doc=parseHTML(await z.file('word/document.xml').async('string')).document;const texts=[...doc.querySelectorAll('w\\:t')].map(x=>x.textContent);const curCtx=state.currentGeneratedRph,L2=curCtx.approvedLibrary.lesson,joined=texts.join('\n');assert.ok(joined.includes(L2.title||L2.source_title),'title');assert.ok(joined.includes(L2.objective),'objective');assert.ok(joined.includes(L2.sp_code),'sp code');for(const g of ['Kelompok Peneroka','Kelompok Pembina','Kelompok Pencabar'])assert.ok(joined.includes(g),g);for(const sec of ['A. MAKLUMAT PENGAJARAN','E. PDP TERBEZA','F. PENTAKSIRAN BILIK DARJAH (PBD)','G. PENUTUP DAN REFLEKSI'])assert.ok(joined.includes(sec),sec);assert.ok(joined.includes('D. AKTIVITI SUMBER DARIPADA BUKU')||joined.includes('D. ALIRAN AKTIVITI'),'D');});
await test('Unknown/held session is blocked in real canonical path before old blueprint',async()=>{setup(data.entries[0]);map.week_no=34;map.session_no=3;document.getElementById('rphWeek').value='34';await assert.rejects(c.generateRphContent(),e=>e.code==='HELD_SUBFOCUS');assert.equal(oldBlueprintCalls,0);});
await test('Session and revision form part of actual app export filename',()=>{const ctx={classId,subjectId,week:29,date:'2026-10-05',map:{session_no:2},savedRecordVersion:{revision_no:3}};assert.match(c.generatedRphFileName(ctx),/_M29_S2_2026-10-05_V3\.docx$/);});
const report={status:'PASS',checks:checks.length,names:checks,rows,old_blueprint_calls:oldBlueprintCalls,scope:'Real canonical functions in Node VM with DOM, actual approved JSON and real Word ZIP. Auth/source transport and database RPC are controlled TEST fixtures, not authenticated production execution.'};fs.writeFileSync(new URL('canonical-flow-test-report.json',work),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:'PASS',checks:checks.length,canonical_sessions:rows.length,old_blueprint_calls:oldBlueprintCalls}));
