import fs from 'node:fs';
import assert from 'node:assert/strict';
const f=fs.readFileSync(new URL('../rph-science-year2-unit9-source-blueprint-hotfix.js',import.meta.url),'utf8');
const routeMatches=[...f.matchAll(/"9\.[12]\.\d@\d+\|W\d+\|S\d+":"w\d+s\d+"/g)].map(x=>x[0]);
assert.equal(routeMatches.length,15,'Unit 9 must contain exactly 15 exact routes');
const reviewBlock=f.match(/const REVIEW=new Set\(\[([\s\S]*?)\]\);/)?.[1]||'';
assert.equal((reviewBlock.match(/\|W\d+\|S\d+"/g)||[]).length,8,'Unit 9 review set must contain 8 routes');
assert.ok(!/\|W32\||\|W36\|/.test(routeMatches.join('\n')),'Unit 9 must not route W32 or W36');
for(const p of [111,115]) assert.ok(!new RegExp(`@${p}\\|W`).test(routeMatches.join('\n')),`Printed page ${p} must not be invented as exact route`);
assert.ok(f.includes("activityLibraryPolicy:'Activity Library may vary delivery only and must not determine lesson content'"));
assert.ok(f.includes("activityBookPolicy:'Buku Aktiviti tidak digunakan sebagai sumber kandungan blueprint ini; jangan reka aktiviti Buku Aktiviti.'"));
assert.ok(f.includes("weekPolicy:'Blueprint ini hanya W33-W35. W36 bermula Unit 10 Teknologi.'"));
assert.ok(f.includes("9.2.2@112|W35|S2"),'Expected gas/SP mismatch route must remain exact');
assert.ok(f.includes("9.2.5@116|W35|S5"),'Expected final source route must remain exact');
assert.ok(!f.includes('Math.random'));
assert.ok(!f.includes("mappingStatus:'VERIFIED'"));
assert.ok(!f.includes('mappingStatus:"VERIFIED"'));
assert.ok(f.includes("generateFlag:'YES'"));
assert.ok(f.includes('conditional:false'));
console.log('Science Year 2 Unit 9 source-first blueprint static guard passed: 15 routes; alignment review: 8 conditional: 0');