import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../rph-science-year2-unit1-source-blueprint-hotfix.js',import.meta.url),'utf8');
const routes=[...src.matchAll(/"(1\.[12]\.\d@\d+\|W(?:2|3|4|5|7|8|9|10)\|S[1-5])":"w\d+s\d"/g)].map(x=>x[1]);
assert.equal(routes.length,40,'expected 40 Year 2 early-unit routes');
assert.equal(new Set(routes).size,40,'routes must be unique');
for(const w of [2,3,4,5,7,8,9,10])for(let s=1;s<=5;s++)assert(routes.some(r=>r.includes(`|W${w}|S${s}`)),`missing W${w} S${s}`);
assert(!src.includes('|W6|'),'W6 is holiday and must not be routed');
assert(!src.includes('|W11|'),'W11 belongs Peraturan Bilik Sains');
const review=src.match(/const REVIEW=new Set\(\[([\s\S]*?)\]\);/)?.[1]||'';
assert.equal((review.match(/"1\./g)||[]).length,10,'expected 10 alignment-review routes');
const conditional=src.match(/const CONDITIONAL=new Set\(([^;]+)\);/)?.[1]||'';
assert(conditional.includes("|W10|"),'W10 must be conditional');
assert(src.includes("generateFlag:conditional?'CONDITIONAL':'YES'"));
assert(src.includes('Activity Library may vary delivery only and must not determine lesson content'));
assert(src.includes('W6 ialah cuti Tahun Baru Cina'));
assert(src.includes('W10 kekal CONDITIONAL'));
assert(!src.includes('Math.random'));
assert(!/mappingStatus\s*:\s*['"]VERIFIED['"]/.test(src));
assert(!/verification_status\s*:\s*['"]VERIFIED['"]/.test(src));
console.log('Science Year 2 early source-first blueprint static guard passed: 40 routes; alignment review: 10 conditional: 5');
