import fs from 'node:fs';
const src=fs.readFileSync(new URL('../rph-science-year2-unit6-source-blueprint-hotfix.js',import.meta.url),'utf8');
const routes=[...src.matchAll(/"(6\.1\.[1-6]@\d+\|W2[4-6]\|S[1-5])":"w/g)].map(m=>m[1]);
if(routes.length!==15)throw new Error(`expected 15 routes, got ${routes.length}`);
if(new Set(routes).size!==15)throw new Error('duplicate Unit 6 route');
for(const w of [24,25,26])for(let s=1;s<=5;s++)if(!routes.some(r=>r.includes(`|W${w}|S${s}`)))throw new Error(`missing W${w} S${s}`);
if(routes.some(r=>/\|W(23|27)\|/.test(r)))throw new Error('route leaked outside W24-W26');
const reviewBlock=(src.match(/const REVIEW=new Set\(\[([\s\S]*?)\]\);/)||[])[1]||'';
const reviewCount=(reviewBlock.match(/\|W2[4-6]\|S/g)||[]).length;
if(reviewCount!==4)throw new Error(`expected 4 alignment reviews, got ${reviewCount}`);
if(!src.includes("const CONDITIONAL=new Set(Object.keys(ROUTES).filter(k=>k.includes('|W26|')))"))throw new Error('W26 conditional set missing');
if(!src.includes("generateFlag:conditional?'CONDITIONAL':'YES'"))throw new Error('conditional Generate_Flag semantics missing');
if(!src.includes('26.07.2026-30.07.2026'))throw new Error('W26 date anomaly policy missing');
if(src.includes('Math.random'))throw new Error('Math.random forbidden');
if(/mappingStatus\s*:\s*['\"]VERIFIED['\"]/.test(src))throw new Error('must not force VERIFIED');
if(!src.includes('Activity Library may vary delivery only and must not determine lesson content'))throw new Error('Activity Library policy missing');
if(!src.includes('jangan reka aktiviti Buku Aktiviti'))throw new Error('activity book invention guard missing');
if(!src.includes('Mencipta Permainan Wayang Kertas'))throw new Error('p70 source task missing');
if(!src.includes('Saya Jawab — Terang dan Gelap'))throw new Error('p72 source task missing');
console.log(`Science Year 2 Unit 6 source-first blueprint static guard passed: ${routes.length} routes; alignment review: ${reviewCount} conditional: 5`);