import fs from 'node:fs';
const src=fs.readFileSync('rph-science-year2-unit8-source-blueprint-hotfix.js','utf8');
const loader=fs.readFileSync('app-v03334.js','utf8');
const routes=new Set([...src.matchAll(/"8\.1\.[1-5]@\d+\|W(?:31|32)\|S[1-5]"/g)].map(x=>x[0]));
if(routes.size!==10)throw new Error(`expected 10 routes, got ${routes.size}`);
for(const w of [31,32])for(let s=1;s<=5;s++)if(![...routes].some(r=>r.includes(`|W${w}|S${s}`)))throw new Error(`missing W${w} S${s}`);
if(/\|W(?:30|33)\|/.test([...routes].join('\n')))throw new Error('boundary leak');
for(const p of [89,91,95,99])if(new RegExp(`@${p}\\|W`).test(src))throw new Error(`invented page ${p} route`);
for(const p of [87,88,90,92,93,94,96,97,98,100])if(!new RegExp(`@${p}\\|W`).test(src))throw new Error(`missing mapped page ${p}`);
const reviewBlock=src.match(/const REVIEW=new Set\(\[(.*?)\]\);/s)?.[1]||'';
const reviews=(reviewBlock.match(/W(?:31|32)/g)||[]).length;
if(reviews!==3)throw new Error(`expected 3 alignment reviews, got ${reviews}`);
if(src.includes('Math.random'))throw new Error('Math.random forbidden');
if(src.includes("mappingStatus:'VERIFIED'")||src.includes('mappingStatus:"VERIFIED"'))throw new Error('must not force VERIFIED');
if(!src.includes("generateFlag:'YES'")||!src.includes('conditional:false'))throw new Error('Generate_Flag semantics changed');
if(!src.includes('Activity Library may vary delivery only and must not determine lesson content'))throw new Error('activity-library policy missing');
if(!src.includes('jangan reka aktiviti Buku Aktiviti'))throw new Error('activity-book policy missing');
const u7=loader.indexOf('rph-science-year2-unit7-source-blueprint-hotfix.js');
const u8=loader.indexOf('rph-science-year2-unit8-source-blueprint-hotfix.js');
const eng=loader.indexOf('rph-english-year2-unit5-source-blueprint-hotfix.js');
if(!(u7>=0&&u8>u7&&eng>u8))throw new Error('loader order must be Unit 7 -> Unit 8 -> English');
console.log(`Science Year 2 Unit 8 source-first blueprint static guard passed: ${routes.size} routes; alignment review: ${reviews} conditional: 0`);