import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../rph-science-year1-unit8-source-blueprint-hotfix.js',import.meta.url),'utf8');
const routes=[...src.matchAll(/"(8\.1\.\d@\d+\|W(?:31|32|33)\|S[1-5])":"w\d+s\d"/g)].map(x=>x[1]);
assert.equal(routes.length,15,'expected exactly 15 Unit 8 routes');
assert.equal(new Set(routes).size,15,'Unit 8 routes must be unique');
for(const w of [31,32,33])for(let s=1;s<=5;s++)assert(routes.some(r=>r.includes(`|W${w}|S${s}`)),`missing W${w} S${s}`);
assert(!src.includes('|W30|'),'must not include Unit 7 W30');
assert(!src.includes('|W34|'),'must not include Unit 9 W34');
for(const p of [71,72,76,79,80])assert(src.includes(`@${p}|`),`missing mapped printed page ${p}`);
for(const p of [73,74,75,77,78])assert(!src.includes(`@${p}|`),`must not invent exact route for unmapped page ${p}`);
const reviewBlock=src.match(/const REVIEW=new Set\(\[([\s\S]*?)\]\);/)?.[1]||'';
assert.equal((reviewBlock.match(/"8\.1\./g)||[]).length,8,'expected 8 alignment-review routes');
assert(src.includes("generateFlag:'YES'"),'all Unit 8 routes should be YES');
assert(src.includes('conditional:false'),'Unit 8 has no conditional routes');
assert(src.includes('sourceContinuationPolicy'),'must preserve p72 continuation provenance');
assert(src.includes('legacyHelperPolicy'),'must document legacy absorption helper fallback policy');
assert(src.includes('Activity Library may vary delivery only and must not determine lesson content'));
assert(src.includes('Buku Aktiviti tidak digunakan sebagai sumber kandungan dalam blueprint ini; jangan reka aktiviti Buku Aktiviti.'));
assert(!src.includes('Math.random'));
assert(!/mappingStatus\s*:\s*['"]VERIFIED['"]/.test(src));
assert(!/verification_status\s*:\s*['"]VERIFIED['"]/.test(src));
console.log('Science Year 1 Unit 8 source-first blueprint static guard passed: 15 routes; alignment review: 8 conditional: 0');
