import fs from 'node:fs';
const p='rph-science-year2-units2-3-source-blueprint-hotfix.js';
const s=fs.readFileSync(p,'utf8');
const routeMatches=[...s.matchAll(/"(\d+\.\d+\.\d+@\d+\|W\d+\|S\d+)":"w\d+s\d+"/g)].map(m=>m[1]);
const uniq=new Set(routeMatches);
if(routeMatches.length!==25||uniq.size!==25)throw new Error(`Expected 25 unique routes, got ${routeMatches.length}/${uniq.size}`);
const cond=[...uniq].filter(k=>k.includes('|W15|'));
if(cond.length!==5)throw new Error(`Expected 5 W15 conditional routes, got ${cond.length}`);
if([...uniq].some(k=>/\|W(10|16)\|/.test(k)))throw new Error('Route leaked outside W11-W15');
if(!s.includes("const CONDITIONAL_NOTE='W15 ialah partial teaching week."))throw new Error('Missing W15 conditional policy');
if(!s.includes("Unit 4 Haiwan bermula W16 dan tidak diroute di sini."))throw new Error('Missing W16 boundary guard');
if(!s.includes("Activity Library may vary delivery only and must not determine lesson content"))throw new Error('Missing Activity Library policy');
if(!s.includes("jangan reka aktiviti Buku Aktiviti"))throw new Error('Missing activity-book non-invention policy');
if(s.includes('Math.random'))throw new Error('Math.random is forbidden');
if(/mappingStatus\s*:\s*['"]VERIFIED['"]/.test(s))throw new Error('Must not force VERIFIED');
const reviewBlock=s.match(/const REVIEW=new Set\(\[([\s\S]*?)\]\);/);
if(!reviewBlock)throw new Error('Missing REVIEW set');
const reviewCount=(reviewBlock[1].match(/"\d+\.\d+\.\d+@\d+\|W\d+\|S\d+"/g)||[]).length;
if(reviewCount!==11)throw new Error(`Expected 11 alignment-review routes, got ${reviewCount}`);
console.log(`Science Year 2 Units 2-3 source-first blueprint static guard passed: ${routeMatches.length} routes; alignment review: ${reviewCount} conditional: ${cond.length}`);