import fs from 'node:fs';
const src=fs.readFileSync('rph-science-year3-unit10-source-blueprint-hotfix.js','utf8');
const die=m=>{throw new Error(m)};
if(!src.includes("for(const w of [36,37])"))die('missing W36-W37 route generator');
for(const token of ["['10.1.1',128]","['10.1.2',129]","['10.1.3',131]","['10.1.4',133]","['10.1.5',135]"])if(!src.includes(token))die(`missing standard ${token}`);
if(!src.includes('const REVIEW=new Set();'))die('Unit 10 should have zero alignment review routes');
if(!src.includes('W38 ialah Revision'))die('W38 revision boundary missing');
if(/\|W(?:35|38)\|S/.test(src))die('route leaked outside W36-W37');
if(src.includes('Math.random'))die('Math.random forbidden');
if(/mappingStatus\s*:\s*['"]VERIFIED['"]/.test(src))die('must not force VERIFIED');
if(!src.includes('Activity Library may vary delivery only and must not determine lesson content'))die('activity library policy missing');
if(!src.includes('jangan reka aktiviti Buku Aktiviti'))die('activity book guard missing');
if(!src.includes('alat tajam atau kerja memotong dikendalikan atau diawasi guru'))die('model safety guard missing');
if(!src.includes("window.rphScienceYear3Unit10SourceBlueprint=blueprint"))die('export missing');
if(!src.includes('conditional:[]'))die('Unit 10 conditional list must be empty');
console.log('Science Year 3 Unit 10 source-first blueprint static guard passed: 10 routes; alignment review: 0 conditional: 0');