import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../rph-science-year3-unit3-source-blueprint-hotfix.js',import.meta.url),'utf8');
const routeMatches=[...src.matchAll(/'([0-9.]+@\d+\|W\d+\|S\d+)':'w\d+s\d+'/g)].map(m=>m[1]);
assert.equal(routeMatches.length,25,'must have exactly 25 routes');
assert.equal(new Set(routeMatches).size,25,'routes must be unique');
assert(routeMatches.every(r=>/\|W(?:12|13|14|15|16)\|S[1-5]$/.test(r)),'routes must stay within W12-W16');
assert(!src.includes('|W11|')&&!src.includes('|W17|'),'must not route W11 or W17');
const allowedPages=new Set([30,32,34,37,44,47,49,50,52,54]);
for(const r of routeMatches){const p=Number(r.match(/@(\d+)\|/)[1]);assert(allowedPages.has(p),`unexpected page ${p}`)}
const reviewSection=src.match(/const REVIEW=new Set\(\[([^\]]*)\]\);/s)?.[1]||'';
const reviews=[...reviewSection.matchAll(/'([^']+)'/g)].map(m=>m[1]);
assert.equal(reviews.length,3,'must have exactly 3 alignment-review routes');
assert(reviews.includes('3.1.5@37|W12|S5'));
assert(reviews.includes('3.2.5@47|W13|S3'));
assert(reviews.includes('3.2.5@47|W14|S3'));
assert(!src.includes("'3.2.1@")&&!src.includes("'3.2.2@"),'must not silently add unscheduled 3.2.1/3.2.2 routes');
assert(src.includes("dskpGapPolicy:'RPT sumber bagi 3.2 hanya menjadualkan SP 3.2.3-3.2.5. SP 3.2.1-3.2.2 tidak ditambah secara senyap.'"));
assert(src.includes("activityLibraryPolicy:'Activity Library may vary delivery only and must not determine lesson content'"));
assert(src.includes("activityBookPolicy:'Buku Aktiviti tidak digunakan sebagai sumber kandungan blueprint ini; jangan reka aktiviti Buku Aktiviti.'"));
assert(src.includes("generateFlag:'YES'"));
assert(src.includes('conditional:false'));
assert(!src.includes('Math.random'));
assert(!src.includes("mappingStatus:'VERIFIED'"));
assert(!src.includes('mapping_status:"VERIFIED"'));
assert(src.includes('window.rphScienceYear3Unit3SourceBlueprint=blueprint'));
console.log(`Science Year 3 Unit 3 source-first blueprint static guard passed: ${routeMatches.length} routes; alignment review: ${reviews.length} conditional: 0`);
const loader=fs.readFileSync(new URL('../app-v03334.js',import.meta.url),'utf8');
const helperA=loader.indexOf('rph-science-year3-source-blueprint-hotfix.js');
const helperB=loader.indexOf('rph-science-year3-future-blueprint-hotfix.js');
const early=loader.indexOf('rph-science-year3-early-source-blueprint-hotfix.js');
const unit3=loader.indexOf('rph-science-year3-unit3-source-blueprint-hotfix.js');
const english=loader.indexOf('rph-english-year2-unit5-source-blueprint-hotfix.js');
assert(helperA>=0&&helperB>helperA&&early>helperB&&unit3>early&&english>unit3,'loader order must be helpers -> early -> unit3 -> English');
assert.equal((loader.match(/rph-science-year3-unit3-source-blueprint-hotfix\.js/g)||[]).length,1,'Unit 3 loader must appear exactly once');
console.log('Science Year 3 Unit 3 loader order guard passed.');
