import fs from 'node:fs';
const src=fs.readFileSync('rph-lessonmap-live-verify-gate-hotfix.js','utf8');
const loader=fs.readFileSync('app-v03334.js','utf8');
const die=m=>{throw new Error(m)};
for(const token of ['function reconstructScienceQuestionTasks','function cleanScienceOcrLine','function stripScienceOcrTail','function cleanScienceActivityText','_runtime_science_ocr_question_reconstructed:true','scienceOcrQuestionRepair:true','scienceOcrTailCleanup:true'])if(!src.includes(token))die(`missing ${token}`);
if(!src.includes("/\\b(?:dari|tanpa)\\s*[.,;:]?$/i"))die('dari/tanpa truncated-tail guard missing');
if(!src.includes("/(\\?)(?:\\s+[A-Za-z0-9]{1,3}[!.,;:]*){1,4}\\s*$/"))die('short OCR glyph tail stripper missing');
if(!loader.includes('rph-lessonmap-live-verify-gate-hotfix.js?v=20260906d'))die('cache-bust loader missing');
if(src.includes('Math.random'))die('Math.random forbidden');
console.log('Science OCR reconstruction guard passed: multiline questions rebuilt and trailing diagram glyphs removed.');
