import fs from 'node:fs';
import assert from 'node:assert/strict';
const file='rph-science-year1-unit6-source-blueprint-hotfix.js';
const src=fs.readFileSync(new URL(`../${file}`,import.meta.url),'utf8');
const loader=fs.readFileSync(new URL('../app-v03334.js',import.meta.url),'utf8');
const routeBlock=(src.match(/const ROUTES=\{([\s\S]*?)\n\};/)||[])[1]||'';
const routes=[...routeBlock.matchAll(/"([^"]+)":"w\d+s\d+"/g)].map(m=>m[1]);
const reviewBlock=(src.match(/const REVIEW=new Set\(\[([\s\S]*?)\]\);/)||[])[1]||'';
const reviews=[...reviewBlock.matchAll(/"([^"]+)"/g)].map(m=>m[1]);
assert.equal(routes.length,15,'Unit 6 must expose exactly 15 W25-W27 routes');
assert.equal(new Set(routes).size,15,'Unit 6 routes must be unique');
assert.equal(reviews.length,8,'Unit 6 must keep exactly 8 alignment-review routes');
assert.ok(reviews.every(r=>routes.includes(r)),'Every review route must exist in ROUTES');
assert.ok(routes.every(r=>/\|W(25|26|27)\|S[1-5]$/.test(r)),'Only W25-W27 routes are allowed');
assert.ok(!routes.some(r=>/\|W(24|28)\|/.test(r)),'Do not cross Unit 5 or Unit 7 boundary');
assert.ok(routes.every(r=>['51','52','53','56','58','59','60'].includes((r.match(/@(\d+)\|/)||[])[1])),'Only exact mapped printed pages are allowed');
for(const p of ['54','55','57']) assert.ok(!routes.some(r=>r.includes(`@${p}|`)),`Do not invent route for BT p.${p}`);
assert.ok(src.includes('sourceSectionAudit'),'Must preserve source-section mismatch audit');
assert.ok(src.includes('ciri bahagian tumbuhan yang berbeza'),'Actual p.53 source focus must be retained');
assert.ok(src.includes('Activity Library may vary delivery only and must not determine lesson content'));
assert.ok(!src.includes('Math.random'));
assert.ok(!src.includes("mappingStatus:'VERIFIED'"));
assert.ok(!src.includes('mappingStatus:"VERIFIED"'));
assert.ok(src.includes("generateFlag:'YES'"));
assert.ok(src.includes('conditional:false'));
const marker='rph-science-year1-unit6-source-blueprint-hotfix.js?v=20260905a';
assert.equal(loader.split(marker).length-1,1,'Loader must include Unit 6 exactly once');
const a=loader.indexOf('rph-science-year1-unit5-source-blueprint-hotfix.js?v=20260905a');
const b=loader.indexOf(marker);
const c=loader.indexOf('rph-english-year2-unit5-source-blueprint-hotfix.js?v=20260905a');
assert.ok(a>=0&&b>a&&c>b,'Loader order must be Unit 5 -> Unit 6 -> English');
console.log(`Science Year 1 Unit 6 source-first blueprint static guard passed: ${routes.length} routes; alignment review: ${reviews.length} conditional: 0`);