import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../rph-science-year2-unit10-source-blueprint-hotfix.js',import.meta.url),'utf8');
const loader=fs.readFileSync(new URL('../app-v03334.js',import.meta.url),'utf8');
const routeMatches=[...src.matchAll(/"10\.1\.[1-6]@\d+\|W(?:36|37|38)\|S[1-5]":"w\d+s\d"/g)];
assert.equal(routeMatches.length,15,'expected 15 exact W36-W38 routes');
const reviewBlock=src.match(/const REVIEW=new Set\(\[(.*?)\]\);/s)?.[1]||'';
assert.equal((reviewBlock.match(/\|W(?:36|37|38)\|/g)||[]).length,4,'expected 4 alignment-review routes');
assert.ok(!src.includes('|W35|')&&!src.includes('|W39|'),'must not route W35 or W39');
for(const p of [117,118,119,120,121,122,123,124,125,126,127,128,129]) assert.ok(src.includes(`@${p}|`)||src.includes(`"${p}|`),`expected mapped page ${p}`);
assert.ok(src.includes('10.1.3@124|W37|S3')&&src.includes('10.1.4@124|W37|S4'),'p124 must preserve distinct SP routes');
assert.ok(src.includes('10.1.5@128|W38|S3')&&src.includes('10.1.6@128|W38|S4'),'p128 must preserve distinct SP routes');
assert.ok(src.includes("Activity Library may vary delivery only and must not determine lesson content"));
assert.ok(src.includes('Buku Aktiviti tidak digunakan sebagai sumber kandungan blueprint ini; jangan reka aktiviti Buku Aktiviti.'));
assert.ok(src.includes('DSKP_NOTE')&&src.includes('10.1.6'),'must preserve DSKP 10.1.6 context note');
assert.ok(!src.includes('Math.random'));
assert.ok(!src.includes("mappingStatus:'VERIFIED'")&&!src.includes('mappingStatus:"VERIFIED"'));
assert.ok(src.includes("generateFlag:'YES'")&&src.includes('conditional:false'));
const helper=loader.indexOf('rph-science-year2-technology-blueprint-hotfix.js');
const u9=loader.indexOf('rph-science-year2-unit9-source-blueprint-hotfix.js');
const u10=loader.indexOf('rph-science-year2-unit10-source-blueprint-hotfix.js');
const english=loader.indexOf('rph-english-year2-unit5-source-blueprint-hotfix.js');
assert.ok(helper>=0&&u9>=0&&u10>u9&&u10>helper&&english>u10,'loader order must keep helper fallback then Unit9 -> Unit10 -> English');
assert.equal((loader.match(/rph-science-year2-unit10-source-blueprint-hotfix\.js/g)||[]).length,1,'Unit10 loader exactly once');
console.log('Science Year 2 Unit 10 source-first blueprint static guard passed: 15 routes; alignment review: 4 conditional: 0');