import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../rph-science-year1-unit10-source-blueprint-hotfix.js',import.meta.url),'utf8');
const routes=[...src.matchAll(/"(10\.1\.\d@\d+\|W(?:36|37)\|S[1-5])":"w\d+s\d"/g)].map(x=>x[1]);
assert.equal(routes.length,10,'expected exactly 10 Unit 10 routes');
assert.equal(new Set(routes).size,10,'Unit 10 routes must be unique');
for(const w of [36,37])for(let s=1;s<=5;s++)assert(routes.some(r=>r.includes(`|W${w}|S${s}`)),`missing W${w} S${s}`);
for(const w of [35,38,39,40,41,42])assert(!src.includes(`|W${w}|`),`must not route W${w}`);
for(const p of [89,90,92,95,96,97])assert(src.includes(`@${p}|`),`missing mapped printed page ${p}`);
for(const p of [91,93,94])assert(!src.includes(`@${p}|`),`must not invent exact route for continuation page ${p}`);
const reviewBlock=src.match(/const REVIEW=new Set\(\[([\s\S]*?)\]\);/)?.[1]||'';
assert.equal((reviewBlock.match(/"10\.1\./g)||[]).length,5,'expected 5 alignment-review routes');
assert(src.includes("generateFlag:'YES'"),'Unit 10 routes should be YES');
assert(src.includes('conditional:false'),'Unit 10 itself has no conditional routes');
assert(src.includes('W38 ialah Revision CONDITIONAL tanpa SP/page anchor khusus'),'must guard teacher-selected W38 revision');
assert(src.includes('W39-W40 ialah UASA NO; W41-W42 Pengurusan Akhir Tahun NO'),'must guard assessment/end-year boundary');
assert(src.includes('sourceContinuationPolicy'),'must preserve p92-p94 continuation provenance');
assert(src.includes('Activity Library may vary delivery only and must not determine lesson content'));
assert(src.includes('Buku Aktiviti tidak digunakan sebagai sumber kandungan dalam blueprint ini; jangan reka aktiviti Buku Aktiviti.'));
assert(!src.includes('Math.random'));
assert(!/mappingStatus\s*:\s*['"]VERIFIED['"]/.test(src));
assert(!/verification_status\s*:\s*['"]VERIFIED['"]/.test(src));
console.log('Science Year 1 Unit 10 source-first blueprint static guard passed: 10 routes; alignment review: 5 conditional: 0');