#!/usr/bin/env python3
"""Build the local BM1 pilot application bundle and a persistent read-first guide."""
from pathlib import Path
import shutil,json,hashlib,zipfile
R=Path('/data/data/com.termux/files/home/rph-hub');W=R/'rph-library/generated/bm1-library-safe-pilot-r1';APP=W/'app';APP.mkdir(exist_ok=True)
files=[R/'rph-record-versions.js',R/'rph-approved-library.js',R/'rph-record-history-ui.js']
# jszip browser asset is not available from the repository; pilot can still render/read snapshots, while Word uses the local tested module bundle separately.
for p in files:shutil.copy2(p,APP/p.name)
config={
 'dataset':'approved-bm1-library.json','dataset_sha256':hashlib.sha256((APP/'approved-bm1-library.json').read_bytes()).hexdigest(),
 'enabled_ids':['BM1-2026B-W29-S1','BM1-2026B-W29-S2','BM1-2026B-W29-S3','BM1-2026B-W29-S4','BM1-2026B-W29-S5'],
 'local_pilot_only':True,'production_active':False,'database_remote_configured':False}
(APP/'pilot-config.js').write_text('window.RPH_PILOT_CONFIG='+json.dumps(config,ensure_ascii=False)+';\n')
(APP/'pilot.js').write_text("""(async function(){'use strict';
const cfg=window.RPH_PILOT_CONFIG, $=id=>document.getElementById(id), a=window.RphRecordVersions,b=window.RphApprovedLibrary;
let data=null,current=null,store=null;const owner='11111111-1111-4111-8111-111111111111',classId='22222222-2222-4222-8222-222222222222',subjectId='33333333-3333-4333-8333-333333333333';
function status(t,error=false){$('status').textContent=t;$('status').dataset.error=error?'1':'0'}
function block(){const l=$('blocked-routes');l.replaceChildren(...data.blocked_routes.map(x=>{const li=document.createElement('li');li.textContent=`M${x.week} S${x.session} — ${x.reason} (${x.status})`;return li}))}
function selected(){return data.entries.find(x=>x.week===Number($('week').value)&&x.session===Number($('session').value))}
function mapFor(e){const t=b.mapTemplate(data,e);return {...t,id:crypto.randomUUID(),subject_id:subjectId,confidence_score:100,verification_status:'verified',source_evidence:{...t.source_evidence,textbook:true,meta:{...t.source_evidence.meta,verification_scope:'LOCAL_PILOT_DERIVED_SOURCE'}}}}
function renderMap(e){const m=mapFor(e);$('map-info').textContent=JSON.stringify({id:m.id,week:m.week_no,session:m.session_no,sp:m.sp,pages:[m.textbook_page_start,m.textbook_page_end],approved_id:e.id,content_sha256:e.content_sha256},null,2)}
function fill(){const w=Number($('week').value),items=data.entries.filter(x=>x.week===w);$('session').replaceChildren(...items.map(x=>new Option('S'+x.session+' — '+x.lesson.source_title,x.session)));const e=selected();$('route-info').textContent=e?`${e.id} · ${e.lesson.activity_name} · 60 minit · versi ${e.content_origin_version}`:'';if(e){renderMap(e);$('conditional-row').hidden=!e.source_conditional;$('singing-row').hidden=!e.requires_teacher_singing_model;$('generate').disabled=false;}}
function controls(){const w=$('week'),weeks=[...new Set(data.entries.map(x=>x.week))];w.replaceChildren(...weeks.map(x=>new Option('M'+x,x)));w.value=29;w.onchange=fill;$('session').onchange=fill;fill();block();$('lesson-date').value=new Date().toISOString().slice(0,10)}
function context(e){const m=mapFor(e);const opts={subjectKey:'bm',classId,className:$('class-name').value||'Kelas percubaan',teacherName:$('teacher').value,date:$('lesson-date').value,lessonTime:$('lesson-time').value||'60 minit',duration:60,confirmConditional:$('confirm-conditional').checked,confirmSingingModel:$('confirm-singing').checked,localPilot:true};return b.chosenContext(data,m,opts)}
function show(ctx){current=ctx;const blocks=b.contextBlocks(ctx,{text:''});$('preview').innerHTML=b.renderContext(ctx);$('current-controls').hidden=false;$('current-label').textContent=`${ctx.approvedLibrary.id} · kandungan terkunci · eksport hanya daripada snapshot yang diluluskan`;status('RPH dipaparkan daripada snapshot diluluskan. Isi refleksi selepas PdP; jangan ubah kandungan teras.')}
$('generate').onclick=()=>{try{const e=selected();if(!e)return;show(context(e));}catch(err){status(err.code+': '+err.message,true)}};
$('save-version').onclick=async()=>{try{if(!current)return;const reflection={text:$('reflection').value,note:$('implementation-note').value,total:null,present:null,achieved:null,active:null};const snapshot=a.snapshotFromContext(current,{teacherId:owner,classInfo:{name:$('class-name').value||'Kelas percubaan',academic_year:2026},subjectInfo:{name:'Bahasa Melayu'},reflection,exportLines:b.contextBlocks(current,reflection).map(x=>x.text),exportBlocks:b.contextBlocks(current,reflection)});const p=await a.payloadFor(snapshot,crypto.randomUUID());const r=await store.append(snapshot,p.request_id);status(`Versi tempatan V${r.revision_no} disimpan. Rekod lama tidak ditimpa.`);await history();}catch(err){status(err.code||err.message,true)}};
$('word').onclick=async()=>{try{if(!current)return;status('Eksport Word memerlukan JSZip browser asset; guna butang ini selepas asset JSZip disediakan dalam pakej pilot.',true)}catch(err){status(err.message,true)}};
$('text').onclick=()=>{if(!current)return;const e=selected(),txt=b.contextBlocks(current,{text:$('reflection').value,note:$('implementation-note').value}).map(x=>x.text).join('\\n\\n')+'\\n';const blob=new Blob([txt],{type:'text/plain'});a.downloadBlob(blob,`RPH-BM1-M${e.week}-S${e.session}-${$('lesson-date').value}-DRAF.txt`)};
$('print').onclick=()=>{document.body.classList.add('print-current');window.print();setTimeout(()=>document.body.classList.remove('print-current'),500)};
async function history(){const rows=await store.list(owner),h=$('history');h.replaceChildren(...rows.map(r=>{const d=document.createElement('div');d.className='history-row';d.textContent=`${r.snapshot.context.lesson_date} · M${r.week_no} S${r.session_no} · V${r.revision_no} · ${r.snapshot.context.title}`;const btn=document.createElement('button');btn.textContent='Buka';btn.onclick=()=>{$('preview').innerHTML=a.renderSnapshot(r.snapshot)};d.appendChild(btn);return d}))}
$('reload-history').onclick=history;$('backup').onclick=async()=>{const x=await store.backup(owner);a.downloadBlob(new Blob([JSON.stringify(x,null,2)],{type:'application/json'}),'Sandaran-BM1-Pilot.json')};$('restore').onchange=async ev=>{try{const f=ev.target.files[0];if(!f)return;await store.restore(JSON.parse(await f.text()),owner);await history();status('Sandaran dipulihkan dan dibaca balik.')}catch(err){status(err.message,true)}};
try{data=await b.loadDataset(cfg.dataset,cfg.dataset_sha256);b.armLocal(data,{enabledIds:cfg.enabled_ids});store=await a.openLocal('rph-bm1-safe-pilot-r1');controls();await history();status('Pilot tempatan sedia. Tiada rekod production diubah.')}catch(err){status(err.code||err.message,true)}})();
""")
# guide
(W/'panduan.html').write_text('''<!doctype html><meta charset="utf-8"><title>Panduan Pilot BM1</title><style>body{font:16px/1.5 system-ui;max-width:850px;margin:30px auto;padding:0 18px}code,pre{white-space:pre-wrap}li{margin:8px 0}</style><h1>Panduan Pilot RPH BM Tahun 1</h1><p>Pilot tempatan sahaja. Kandungan 38 RPH berhash; hanya M29 S1–S5 diaktifkan untuk ujian. M34 S3 dan slot khas ditolak.</p><h2>Ujian yang dilalui</h2><ul><li>15 ujian simpanan versi tempatan: sesi sama tarikh berasingan, V1/V2, idempotency, pemulihan dan Word XML.</li><li>12 ujian library: 5 sesi pilot + 38 sesi keseluruhan, blok terbeza dan Word berpadanan, 37 route disekat.</li><li>10 ujian smoke RPH Hub asal lulus sebelum perubahan.</li></ul><h2>Batas</h2><ul><li>Tiada database production, Supabase RPC atau import library production.</li><li>Sandaran production belum dibuat kerana tiada credentials/database CLI.</li><li>Word dalam halaman pilot memerlukan asset JSZip browser; ujian Word Node sebenar telah lulus.</li><li>RPH lama kekal sejarah dan tidak ditulis semula.</li></ul>''')
# copy local jszip browser if a usable dist exists, otherwise document the explicit blocker
print(json.dumps({'status':'PILOT_APP_BUILT','app':str(APP),'enabled_ids':config['enabled_ids'],'production_active':False,'database_remote_configured':False}))
